### ISSUE TITLE
Back button style on Edit Media page is broken

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1004]
- Expected output should be as mentioned in below screenshot.
------------------------------------------------------------------------------------------------
![unnamed image 2](https://user-images.githubusercontent.com/15173772/32261162-c281ce98-bef2-11e7-84da-f08e3de5f554.png)
**------------------------------------------------------------------------------------------------**
- Actual output is as mentioned in below screenshot.
![unnamed image 1](https://user-images.githubusercontent.com/15173772/32261187-eb97088e-bef2-11e7-98b8-7fb62e30911e.png)
------------------------------------------------------------------------------------------------
**Remark - Issue specifically presents in `2017` theme**

**Comment by juhi123** [comment]
I have tested this on local, looks good (y)
