### ISSUE TITLE
Not able to see EDIT and DELETE Link on mouse hover effect for the very first uploaded media

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1005]
- **Expected output:** After uploading any media types regardless of any active theme, once the media is uploaded, the user must be able to see the `Edit` and `Delete` link on mouse hover effect.However, the user is able to see redirection link as mentioned on below screenshot.
------------------------------------------------------------------------------------------------
Edit link screen -
![edit link](https://user-images.githubusercontent.com/15173772/32261742-9b70017c-bef6-11e7-94c5-64e0e3ae726e.png)
------------------------------------------------------------------------------------------------
Delete link screen - 
![delete link](https://user-images.githubusercontent.com/15173772/32261748-ad1d2ca6-bef6-11e7-8a4a-39b0834ecbc8.png)
------------------------------------------------------------------------------------------------
- **Actual output:** After uploading any media types regardless of any active theme, once the media is uploaded, **the user has to refresh the page** in order to see the `Edit` and `Delete` link on mouse hover effect.
------------------------------------------------------------------------------------------------
Please check this visual for the same. https://goo.gl/4KvnDy

**Comment by Sidsector9** [comment]
@kjnanda I watched the video, but I am not able to reproduce this issue.
I'm on WordPress 4.9.1

**Comment by kjnanda** [comment]
@Sidsector9 Please check this visual - 

![untitled gif 1](https://user-images.githubusercontent.com/15173772/33827984-435ba1da-de90-11e7-970a-7c06a4747041.gif)

I think you are refreshing the page before you see the `edit and delete` link

**Comment by juhi123** [comment]
@thrijith I am seeing links on hover without pulling your PR

**Comment by juhi123** [comment]
Got the issue, looks good now.
