### ISSUE TITLE
Medial upload in comment - The color of the upload media button should not be changed after the media is uploaded

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1008]
After media is uploaded the upload buttons seems disabled. After the user clicks anywhere on the screen it seems enabled.  This creates the confusion for the user if the button is enabled/disabled.

----------------------------------------------------------------------------------------------------
**Check these screenshots for media upload button state.**

1. After media uploaded
![untitled image](https://user-images.githubusercontent.com/15173772/32312792-a276bd92-bfc5-11e7-9c1b-3127b8cb6d67.png)
----------------------------------------------------------------------------------------------------
2. After media uploaded and the user has clicked somewhere on the screen.
![unnamed image 1](https://user-images.githubusercontent.com/15173772/32312798-aa37a686-bfc5-11e7-8230-0fc32546ca3d.png)

**Comment by thrijith** [comment]
>After media is uploaded the upload buttons seems disabled.
Not able to replicate this particular issue, but it is greyed out if no file is selected.

PR: https://github.com/rtMediaWP/rtMedia/pull/1017 seems to fix it, merged in `pre-release`. Please test it out.

**Comment by kjnanda** [comment]
Checked with the latest version and it is fixed.
