### ISSUE TITLE
After media is edited, I see the errors regarding HTTP Request.

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1009]
**`Test Environment`:**

> 
> 1. Enabled Plugin list with their current version:
> 
> - BuddyPress - 2.9.1
> - Core rtMedia - 4.4.4
> - Nginx Helper - 1.9.10
> 
> 2. Wordpress Version: 4.8.3
> 

Please check the screenshot.

![unnamed image 2](https://user-images.githubusercontent.com/15173772/32314556-726fc1f8-bfce-11e7-984b-026c958b51c4.png)

**Comment by montu1996** [comment]
ISSUED SOLVED:

**Comment by kjnanda** [comment]
Closing this issue since it does not throw any such errors now!
