### ISSUE TITLE
Responsive - I see white bar below the media when opened in lightbox

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1012]
Check this screenshot.
![unnamed image 7](https://user-images.githubusercontent.com/15173772/32321633-bf070c9c-bfe7-11e7-911a-efe6be832be6.png)

**Comment by montu1996** [comment]
This is the magnific-popup.js library issues

**Comment by montu1996** [comment]
i fixed this issue
PR: https://github.com/rtMediaWP/rtMedia/pull/1066

**Comment by juhi123** [comment]
I am not able to reproduce this

**Comment by montu1996** [comment]
if you can open last image ( may be two or three ) in lightbox, you'll get white bar. @juhi123

**Comment by juhi123** [comment]
Now it's fixed 👍
