### ISSUE TITLE
Mov file is not playing

### ISSUE THREAD

**Issue by computer77** [rtMediaWP/rtMedia#1014]
I have used transcode plugins and also used the code snippet to run the mov file but is still not  playing the mov video file. Please let me know ASAP

**Comment by pranali333** [comment]
Hello,

This is Pranali from rtMedia team.

We checked the transcoder plugin at our demo website and is working fine. Please once try enabling any WordPress default theme and deactivating other plugins to avoid any possible conflicts.

>also used the code snippet to run the mov file

Could you please mention what code are you talking about here?

Thanks,

**Comment by pranali333** [comment]
Hello,

We didn't hear back from you.
I hope this issue has been fixed at your end.

I am closing this thread for now. Please feel free to open a new one if you have any query in future.

Thanks,
Pranali
