### ISSUE TITLE
Add filter to customize the existing progress bar and add percentage % to it

### ISSUE THREAD

**Issue by pranali333** [rtMediaWP/rtMedia#1026]
This is the current progress bar for media:

![progress-bar-media-upload](https://user-images.githubusercontent.com/7771963/34413091-21f4cf06-ec07-11e7-9576-faebced950e4.png)

We can add a filter which can allow users to customize this bar for themselves and add the percentage (100%) in terms of progress to it.

Thanks

**Comment by kjnanda** [comment]
@thrijith This looks good now.
