### ISSUE TITLE
Handle the all media type disable condition properly

### ISSUE THREAD

**Issue by pranali333** [rtMediaWP/rtMedia#1027]
This is the enable media-type admin setting screen:

![all-type-disable](https://user-images.githubusercontent.com/7771963/34413274-4949f008-ec08-11e7-8bd4-33f1eae28b27.png)

When all the media type are disabled and anyone tries to upload media, nothing happens. No message, no notice to users. This needs to be handled in the better way.

Thanks

**Comment by kjnanda** [comment]
This is working as expected only for `photo, video and music` data type when they are disabled from setting.

When user has kept enabled `Docs and other files` add-on and if they are enabled from backend then it should allow the user to `upload`. `Which is not happening right now.` 

Please do the needful.

Check this video for more information - https://goo.gl/iipqge

**Comment by kjnanda** [comment]
This is working as expected now.
