### ISSUE TITLE
Check media comment feature when BP activity is disabled

### ISSUE THREAD

**Issue by pranali333** [rtMediaWP/rtMedia#1028]
Here you can find BP activity component:

![bp-activity](https://user-images.githubusercontent.com/7771963/34413485-db607664-ec09-11e7-9d19-b28c7e3649b8.png)

Please follow these steps to regenerate the issue:

1) Disable BP activity
2) Open any media file and try commenting on it using rtMedia
3) check the error log files for possible errors

Thanks

**Comment by kjnanda** [comment]
This is working fine now.

**Comment by kjnanda** [comment]
These options must not be visible if the `Activity Component` is disabled.

![screenshot-krupa rtdemo in 2018-01-02 12-26-52-873](https://user-images.githubusercontent.com/15173772/34476636-83ea67a2-efb8-11e7-8617-314303edc5c7.png)

CC @pranali333 Please add your input.

**Comment by pranali333** [comment]
Rather than removing, we can make it read-only.

**Comment by kjnanda** [comment]
@thrijith Please do the needful.

**Comment by kjnanda** [comment]
@thrijith Above changes works as expected. 
---------------------------------------------------------------------------------------------------
Please check below screenshot.

![settings_ _demo_ _wordpress](https://user-images.githubusercontent.com/15173772/34608513-ab052cc2-f23e-11e7-856f-605d2431e0d0.jpg)

Please do the same change for `Buddypress Group`. If the the Group component is disabled then the relevant changes as should be disabled in rtMedia Settings.

**Comment by juhi123** [comment]
Now looks good
