### ISSUE TITLE
Not allowing to upload - Bug while uploading media from activity feed

### ISSUE THREAD

**Issue by SID177** [rtMediaWP/rtMedia#1056]
When `Show "Terms of Service" checkbox on activity screen` is enabled, upload from activity feed is not working.

Steps to regenerate the issue:

1. enable the above setting.
2. upload media from activity without checking the upload term checkbox
3. it will show you error `Please check terms of service.`
4. once you check this checkbox, there is no way to upload the media.
5. Upload box gets disabled.

**Comment by juhi123** [comment]
@SID177 It's still not working, it working only if I click media icon then click on post update after step 4.

**Comment by SID177** [comment]
Can you give me steps to generate `not working` scenario?

**Comment by juhi123** [comment]
Strange, now it's working @SID177

**Comment by SID177** [comment]
Ohhh. Okay :thinking: :+1:

**Comment by juhi123** [comment]
@thrijith This issue always behaves differently, now when I am checking it's not working until I click in Text area Screencast: https://drive.google.com/file/d/1K0YemlNzbYC70QK5Uj_cgv3ahdVkqMf0/view

**Comment by pranali333** [comment]
Hi @SID177 ,

Is there any specific reason to keep this issue open?

@SID177 Please also check if this issue has been fixed/released.

Thanks

**Comment by kjnanda** [comment]
This issue has been fixed with V4.5.2 [JULY 11, 2018] and hence closing it.
