### ISSUE TITLE
Enqueue scripts and styles

### ISSUE THREAD

**Issue by jomisica** [rtMediaWP/rtMedia#1065]
I really like the plugin. However is there a need to enqueue scripts and styles on all pages?

Why does the plugin not enqueue scripts and styles only when they are needed! It's heavy to have to always download even on pages that do not make sense. Primarily in mobile devices.

**Comment by pranali333** [comment]
Hello,

We have improved the plugin performance with the new release of the plugin.
Please once update to the latest version and let us know if that helps you.

Thanks for your suggestion!
Regards,
Pranali
