### ISSUE TITLE
Light Box Comment Media Height Issues

### ISSUE THREAD

**Issue by montu1996** [rtMediaWP/rtMedia#1070]
when we add media as a comment, lightbox height is going infinitely down and the view is being messed up...  
![screenshot from 2018-03-15 15-29-03](https://user-images.githubusercontent.com/21100078/37512740-f9714bf4-2928-11e8-9763-2647c49488a5.png)
![screenshot from 2018-03-15 15-29-09](https://user-images.githubusercontent.com/21100078/37512741-f9b86282-2928-11e8-8b98-4c6baafae5d2.png)
![screenshot from 2018-03-15 15-29-15](https://user-images.githubusercontent.com/21100078/37512742-f9e4ec3a-2928-11e8-9f74-8781d2f66cb2.png)

**Comment by pranali333** [comment]
@montu1996 Which theme are you using?
What are the back-end media size settings?

Please share screenshot for the same as well.

**Comment by montu1996** [comment]
I'm using **twenty-seventeen** theme...
media size settings: 
![media-size-settings](https://user-images.githubusercontent.com/21100078/37513196-603596e6-292a-11e8-855c-fbd73f6a70e0.png)

**Comment by juhi123** [comment]
Seems fixed now 👍
