### ISSUE TITLE
Duplicate upload nonce ids on activity page

### ISSUE THREAD

**Issue by seventhqueen** [rtMediaWP/rtMedia#1077]
Hi, Since on the activity page on each comment it is rendered the upload form we get errors in browser console related to non-unique id. Please see the attach
![screen shot 2018-03-23 at 09 50 37](https://user-images.githubusercontent.com/3746763/37817610-0720ba8a-2e80-11e8-985f-142587189c07.png)

**Comment by pranali333** [comment]
Hello Seventhqueen,

I have passed your query to the team. We are only experiencing this with the _Kleo_ theme so far. Checking with _Kleo Version: 4.2.12_. 
Our team is still digging into the code and will definitely fix it up if rtMedia is causing this issue.

I will update you soon regarding this.

Thanks for pointing out this to us.
Regards,
Pranali

**Comment by pranali333** [comment]
Hello,

We have cross-checked this issue further and found the following:

- The issue only occurs when the _Kleo_ theme is activated. It works fine with all other default themes of WordPress.

- The console errors are there even when rtMedia plugin is not active. 
Please once try adding normal text comments having:

BuddyPress plugin **active**
Kleo theme **active**
rtMedia **deactivated**

You will still face these errors.
Screenshot:


![kleo-bp-activity-errors](https://user-images.githubusercontent.com/7771963/37828179-3ccf11fa-2ec0-11e8-8b89-5e09f94b9823.png)


- Hence, we request you to once check this issue with your theme developers. We are not sure what can cause this issue.

Please let me know if you have any doubts.

Looking forward to your reply.

Thanks,
Pranali

**Comment by seventhqueen** [comment]
Hi, thanks for looking into this. Will do some more tests and come back with a fix, Thanks

**Comment by seventhqueen** [comment]
I managed to fix this. Hurray 🥇 
The strange fact was the the duplicate IDs were on other themes and not just KLEO but only in Kleo those appeared. 
After some debugging and research I found that those console errors appear only when there is a input type="password" in the page. We had one loading from the login modal :)

Now it is fixed in the latest KLEO theme version. 

Thanks for your time
