### ISSUE TITLE
Load more button breaks with music files thumbnail

### ISSUE THREAD

**Issue by juhi123** [rtMediaWP/rtMedia#1084]
It happens when `Enable Masonry Cascading grid layout` is enabled.

Other settings that I have kept:
Media Sizes Thumbnail Size: 200x150
Number of media per page is 2

![screen shot 2018-03-30 at 4 15 19 pm](https://user-images.githubusercontent.com/8724401/38135474-ea149ab8-3435-11e8-9c87-8203201a1f9a.png)

**Comment by juhi123** [comment]
Looks good

**Comment by thrijith** [comment]
Fixed in rtMedia version 4.5.0

PR Ref: [#1111](https://github.com/rtMediaWP/rtMedia/pull/1111)
