### ISSUE TITLE
Issue with rtMedia Upload By Url - media list keeps blurred even after upload is complete

### ISSUE THREAD

**Issue by SID177** [rtMediaWP/rtMedia#1085]
If I add files from normal `File Upload` tab and then switch to `Url Import`, upload nothing there, and try to upload previously added files, The media list still be blurred even after the upload is complete.  
If I'm on `Url Import` tab, the list won't unblur that's the issue.  
Addon: https://rtmedia.io/products/rtmedia-upload-by-url/

![media-list-duplication](https://user-images.githubusercontent.com/23107546/38186795-5a602880-3672-11e8-87f6-e74bfe1bbb81.png)

Video link: https://drive.google.com/open?id=1sKrS3hkodtrbMOmXm4hNAq92svdMJEeV

**Comment by juhi123** [comment]
@SID177 Working 👍

**Comment by juhi123** [comment]
Looks good on develop branch

**Comment by pranali333** [comment]
Fixed and released with rtMedia V 4.4.7.

Closing this.
