### ISSUE TITLE
rtmedia_gallery method of JSON API not working properly.

### ISSUE THREAD

**Issue by SID177** [rtMediaWP/rtMedia#1099]
Some parameters of JSON API method `rtmedia_gallery` are not parsing properly.

- Passing `media_type` doesn't return media list of specified `media_type`.
- If we don't pass `per_page` parameter, the default value should be `10`, but it returns only 1 media. If we pass `per_page ` as parameter, then only it will return more than 1.

**Comment by juhi123** [comment]
@SID177 It seems to be working now

**Comment by thrijith** [comment]
Fixed in rtMedia version 4.5.0

PR Ref: [#1100](https://github.com/rtMediaWP/rtMedia/pull/1100)
