### ISSUE TITLE
rtmedia - check_condition error

### ISSUE THREAD

**Issue by mickaelmaury** [rtMediaWP/rtMedia#1117]
I have a problem on the following site: https://esprit-zebre.fr where you can register for free. 
This occurs in the "Location" page of a member (eg https://ecclesia-athena.com/members/mickael-maury/location/).

rtmedia.min.js: 7 Uncaught ReferenceError: check_condition is not defined
    at window.onload (rtmedia.min.js: 7)

**Comment by mickaelmaury** [comment]
The debug information as an attachment.
[debuginfo.txt](https://github.com/rtMediaWP/rtMedia/files/2089031/debuginfo.txt)

**Comment by seventhqueen** [comment]
same here, I got the same error out of the blue

**Comment by seventhqueen** [comment]
@mickaelmaury please check that you don't have any php errors that prevent the page from fully loading. At least this was my problem. 

All the best

**Comment by kjnanda** [comment]
Hi @mickaelmaury ,

It is been long we haven't heard from you. Can you please update on this query? Are you still facing the same problem? 

Please let us know so that we can take action on this issue.

Regards,
Krupa

**Comment by kjnanda** [comment]
It seems like an issue has been fixed. I am closing this ticket.

**Comment by MaximeCulea** [comment]
Hi,

We are facing the same issue out of the blue without any input on how to fix this. Moreover this issue has been closed without any related fix :/

How did you manage that?

Thank you
