### ISSUE TITLE
"Agree terms" validation must be done on back end side

### ISSUE THREAD

**Issue by sudhir-yadav** [rtMediaWP/rtMedia#1146]
Rtmedia > Other settings > Ask user to agree terms 

![image](https://user-images.githubusercontent.com/3166668/41726949-d9eb438e-7590-11e8-9db9-1f0f71a39f81.png)

Step to generate this scenario ->
Now delete the element `<div id="rtm-file_upload-ui" class="rtm-tab-content">` using any debugging tool
and then upload the file. 
![image](https://user-images.githubusercontent.com/3166668/41727380-d4765dca-7591-11e8-9372-3f59120b48e1.png)

It would allow user to upload file without checking the agree option.

**Comment by vermadarsh** [comment]
PR: [#1545](https://github.com/rtMediaWP/rtMedia/pull/1545)

**Comment by kjnanda** [comment]
1. Activty Page (Profile and Group)
2. Media Page
3. Short code

Need to check this scenario as mentioned above.

**Comment by pooja-muchandikar** [comment]
Tested the issue with `pre-release` branch and following are my findings:

**Activity Page - Profile and Group :x:**
1. In nouveau template deleting the element <div id="rtm-file_upload-ui" class="rtm-tab-content"> deletes the media upload button as well.

2. In Nouveau template if the element is deleted after media upload then still able to upload media and post activity without checking the `agree terms` checkbox.

3. In Legacy template if the element is deleted, then able to upload media and activity post even without checking the `agree terms` checkbox.

Refer visual: https://drive.google.com/file/d/1-Norbc77nY8vxfr73yFklCeL09AgpRax/view

---

**Media Page :heavy_check_mark:**
1. On media page if the element is deleted then while uploading media error message is shown and users are not allowed to upload media which is as expected.

---

**Shortcode :heavy_check_mark:**
1. Created uploader shortcode and checked deleting the agree terms element. Tried to upload media and users are not allowed to upload media which is as expected.

cc: @kjnanda

**Comment by pooja-muchandikar** [comment]
@SID177 


Tested with both BuddyPress nouveau and legacy template in Profile activity, group activity and Media page.
Tested the direct upload issue PR with pre-release branch of rtMedia core and direct upload works with following scenarios.

Testing covered following points:
1. Media upload with direct upload enabled and terms of conditions disabled :heavy_check_mark: 
2. Media upload with direct upload disabled and terms of conditions enabled :heavy_check_mark: 
3. Media upload with direct upload enabled and terms of conditions enabled :heavy_check_mark: 
4. Media uploaded with direct upload disabled and terms of conditions disabled :heavy_check_mark: 

---

But `direct upload` with multiple media is not working as expected. 

With direct upload enabled and terms enabled multiple upload is not working, need to explicitly click on post update button which is incorrect. 

Refer visual -> https://drive.google.com/file/d/1FQq3hQcejhdTpjG6bnelpfzOh5diSevU/view

**Comment by pooja-muchandikar** [comment]
@SID177 

Tested the direct upload issue with multiple uploads with pre-release branch of rtMedia core and direct upload works with following scenarios.

- Media upload with direct upload enabled and terms of conditions disabled heavy_check_mark
- Media upload with direct upload disabled and terms of conditions enabled heavy_check_mark
- Media upload with direct upload enabled and terms of conditions enabled heavy_check_mark
- Media uploaded with direct upload disabled and terms of conditions disabled heavy_check_mark

All the above scenarios works with Single media upload and multiple media upload in profile activity, group activity and media page.

**Comment by kjnanda** [comment]
For this issue below test cases should be considered.

**Single Media Upload**

Check below scenario on Activity Page and group page.

- [ ] 1. direct upload is disabled and upload terms disabled
- [ ] 2. direct upload is disabled and upload terms enabled
- [ ] 3. direct upload is enabled and upload terms disabled
- [ ] 4. direct upload is enabled and upload terms enabled

Repeat the above test cases for bulk upload as well.

**Comment by kjnanda** [comment]
Added fix LGTM 👍

**Comment by SID177** [comment]
To fix this issue for sidebar widget addon's uploader, `uploader_terms_condition_request` and `uploader_terms_condition` needs to be added in post data when the file is uploading.
The file upload parameter is set in the addon's JS file so need to make change there.

**Comment by kjnanda** [comment]
This is working as expected and tested with `dev` branch. ✅

**Comment by kjnanda** [comment]
Closing this issue as this has been fixed and release in - V4.6.1
