### ISSUE TITLE
Button for like is blocked

### ISSUE THREAD

**Issue by BarbaraGo** [rtMediaWP/rtMedia#1165]
If I click on the button "like", this stops and remains in the loading phase.
![schermata 2018-07-11 alle 16 15 24](https://user-images.githubusercontent.com/41119335/42577955-cb721126-8525-11e8-9c06-d0c50528707f.png)

**Comment by malavvasita** [comment]
Hello BarbaraGo,

Thank you for the feedback.

We tried regenerating the issue at our end. However, it is working fine for us.

Please check GIF attached below:

![like-button-in-megnific-popup-issue-github](https://user-images.githubusercontent.com/25079043/42619027-775dba86-85d4-11e8-821c-cf9cd0f8f856.gif)

Can you specify which browser ( version ) you are using?

Thanks,

**Comment by BarbaraGo** [comment]
I tried with Chrome, Safari and Firefox and I had the same issue in both 3 browsers.

**Comment by BarbaraGo** [comment]
I deactivated and reactivated likes option and now seems it works, thank you

**Comment by malavvasita** [comment]
Hello @BarbaraGo,

I am closing this ticket as the issue seems to be resolved.

Also, please feel free to ask if you have any query.
Good Day. 

Regards,
rtMedia Team
