### ISSUE TITLE
Issue posting activity update when terms checkbox is enabled.

### ISSUE THREAD

**Issue by dharmin** [rtMediaWP/rtMedia#1167]
The issue is only present in buddypress legacy template.

1. Add anything in activity textarea.
2. Now click the "Post Update" button without checking the upload terms checkbox.
3. Now check the upload terms checkbox and click "Post Update".
4. The activity will not be generated, because "Post Update" button is disabled from 2nd step.

Refer the screencast for ref - https://drive.google.com/file/d/14L5R_20H_8gFORhDXxmZH85kcX2eSMgR/view

**Comment by kjnanda** [comment]
The added fix is working as expected.

**Comment by pooja-muchandikar** [comment]
Tested with `develop` branch and works as expected.

**Comment by pooja-muchandikar** [comment]
Tested with `master` branch and works as expected.
