### ISSUE TITLE
BuddyPress Activity Post Update button click is disabled.

### ISSUE THREAD

**Issue by pranali333** [rtMediaWP/rtMedia#1180]
Here is a video that demonstrates the issue:

https://www.youtube.com/watch?time_continue=28&v=Bqvkqnv-tdg

Please read this thread for more information - 
https://buddypress.org/support/topic/public-message-button-activation/#post-275541

@SID177 Please fix this.

Thanks,
Pranali

**Comment by kjnanda** [comment]
This is working as expected. Looks good to me. 👍

**Comment by pranali333** [comment]
Hi @SID177 ,

Is there any specific reason to keep this issue open?

@SID177 Please also check if this issue has been fixed/released.

Thanks

**Comment by malavvasita** [comment]
Closing this issue.
As mentioned above, it is already been released in rtMedia v4.5.3

CC: @pranali333 @SID177
