### ISSUE TITLE
how to delete file 

### ISSUE THREAD

**Issue by UnitSol** [rtMediaWP/rtMedia#1182]
Hi guys,

I have been facing issue in file deletion.
you can see the path below and I want to delete this file by providing this complete URL to an API.

https://oneballunited.com/wp-content/uploads/rtMedia/users/333/2017/11/cpm_hiring_uiux_1x.png

Thanks in advance.

**Comment by malavvasita** [comment]
Hey there,

Sorry for reaching out to you late,

I would like to inform you that currently there's no direct way to delete file from API by its path, you can delete it using attachment ID related to this attachment and using WordPress API.

Doc Link: https://developer.wordpress.org/rest-api/reference/media/#delete-a-media-item

Please refer this and let us know if you have any query.

Regards,  
rtMedia Team

**Comment by kjnanda** [comment]
Hi @UnitSol 

I assume that this issue has been resolved. I am closing this ticket as of now. Please feel free to open a new ticket in case of any issue you face.

Regards,

Krupa

**Comment by UnitSol** [comment]
> Hi @UnitSol
> 
> I assume that this issue has been resolved. I am closing this ticket as of now. Please feel free to open a new ticket in case of any issue you face.
> 
> Regards,
> 
> Krupa

**The issue is not resolved.**
