### ISSUE TITLE
rtMedia magnific popup for mobile allows to scroll whole HTML body

### ISSUE THREAD

**Issue by malavvasita** [rtMediaWP/rtMedia#1188]
On Desktop, the media opens in a lightbox that ultimately removes the ability to scroll the HTML body while it is open.

This feature is having issue on mobile devices. 
By opening a media item in popup, users can scroll away from it in HTML body.

**Comment by pranali333** [comment]
@malavvasita 

Please, get this tested.

CC: @kjnanda 

Thanks,

**Comment by kjnanda** [comment]
@malavvasita I cross check this fix at my end. I don't see any difference with scrollable area. 

CC @pranali333

**Comment by pooja-muchandikar** [comment]
@malavvasita Tested and the pop-up doesn't scroll entire background, it is working as expected.  Checked using real device as well. :thumbsup:

CC @pranali333

**Comment by malavvasita** [comment]
@pranali333 This issue has been fixed and tested.

Also merged in respective branch :+1:

**Comment by kjnanda** [comment]
This issue has been fixed and released in V4.5.3
