### ISSUE TITLE
[Customer Query - [#2493000]] rtmedia_no_media_found_message_filter is not working

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1248]
Please look into this query.

Check this [link](https://rtmedia.io/ticket/2493000/#followup-281712) for more information.

**Comment by kjnanda** [comment]
@JAshwini This is working as expected now.

**Comment by kjnanda** [comment]
@ashwinij1512 Please do not merge this in `dev-branch`. I need to test some edge cases.

**Comment by kjnanda** [comment]
@ashwinij1512 Tested at my end with looks good to me. 👍

**Comment by pooja-muchandikar** [comment]
Release in version `4.5.5`
