### ISSUE TITLE
Issue with media comments, if rtMedia direct upload is enabled.

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtMediaWP/rtMedia#1283]
**Steps to Reproduce**

1. Enable Direct Upload option
2. Enable upload terms option
3. Go to activity page and post an update ( with text only )
4. Now, comment on the post with normal text, the comment gets posted.
5. Now, comment on the same post with media, observe that since direct upload is enabled, an error is thrown to agree to terms and conditions ( because direct upload is enabled ) which is present in the activity area which is wrong. As we are commenting on the post.
6. Now, again post an update with media ( text and media )
7. Now, go to that post comment section and select media to upload in comment
8. Observe that, the same error is thrown to agree to terms and conditions, ( because direct upload is enabled ) agree and comment.
9. Now, reload the page and check the comment activities generated. Media activity is generated twice in one activity media is shown twice which is wrong.

Refer visual: https://drive.google.com/open?id=1kgmB3WaO57uvAa_h6os3uXlfGe9N4CF-

**Comment by kjnanda** [comment]
Duplicate issue of https://github.com/rtMediaWP/rtMedia/issues/1359
closing this.
