### ISSUE TITLE
[Theme specific] Issue with 2017 - Media is not opening in light box

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1284]
After updating theme 2017 to its latest version ( 2.0 --> 2.1), media is not opening in lightbox even if the lightbox setting is kept on from rtMedia settings.

`Expected Result:` Clicking upon media - it should open in lightbox

`Actual Result:` Clicking upon media it takes the user to media single page

**Note: The issue appears only whie opening media from `Media Page`. The same media is opening in lightbox from actvity page.**

-----

```
Test Environment:

1. WP - 5.1 and 5.0.3
2. Buddypress  - 4.2.0 and 4.1.0
3. rtMedia - 4.5.5 and 4.5.6
4. Themes - 2013 to 2019 - But issue is present in latest 2017 theme only
5. Browser - Chrome, firefox and safari
```

**Comment by surajkrsingh** [comment]
PR:-https://github.com/rtMediaWP/rtMedia/pull/1315

**Comment by pooja-muchandikar** [comment]
@surajkrsingh 

Testing is done, and the changes added works fine. Able to view media in the lightbox in 2017 theme. 
```
Test Environment
WordPress: v5.1.1
rtMedia: Code from **pre-release** branch (v4.5.6)
BuddyPress: v4.2.0 ( Nouveau and Legacy template )
Themes: 2017 theme as the issue was theme specific. Also cross-checked 2012, 2016 and 2019 theme
```

**Comment by kjnanda** [comment]
Media can be opened in lightbox now. TEsted this against dev branch.

**Comment by kjnanda** [comment]
Media can be opened in light box now. Tested this against master branch.
