### ISSUE TITLE
Media is not getting uploaded when direct upload is enabled with TwentySeventeen Theme.

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtMediaWP/rtMedia#1286]
**Steps to Reproduce**
1. Activate Twenty Seventeen theme ( v2.1 )
2. Enable Upload terms option
3. Enable Direct Upload option
4. Go to Media page and select media to upload
5. Since upload terms are enabled error message is shown to agree to terms and conditions
6. Check the upload terms checkbox, and now observe that media is not uploaded. Direct upload is enabled, on checking upload terms checkbox media should directly get uploaded which is not happening. 

Checked with rtMedia v4.5.6, BuddyPress v4.2.0  and Twenty Seventeen Theme v2.1. 

Refer visual: https://drive.google.com/open?id=1tRyhABRLwLDIUSpniVPMw_D5ZuwHr2C4
##

**Comment by pooja-muchandikar** [comment]
The issue with 2017 v2.1 is been fixed in rtMedia Core ( code merged in pre-release branch ) Ref: rtMediaWP/rtMedia#1284

```
Test Environment
WordPress: v5.1.1
rtMedia Core: Code from **pre-release** branch ( v4.5.6 )
BuddyPress: v4.2.0 ( Nouveau and Legacy template )
```

cc: @kjnanda @pranali333

**Comment by kjnanda** [comment]
Both these functionalities are working as expected. Tested against dev branch code.

**Comment by kjnanda** [comment]
Direct Upload functionality is working as expected. Tested against master branch code.
