### ISSUE TITLE
Uploader Button shows out of the Uploader container when more than one short code is being used in same post

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1287]
**Steps :** 

1. Add any short code (Uploader short code) more than one time on same page or post
2. Update post/page and see the uploader container in front end.
3. Observe that the upload button is misaligned except the `very first uploader container`

-----

Please refer the screenshot.

![screenshot-localhost-2019 03 01-12-33-57](https://user-images.githubusercontent.com/15173772/53622101-bda67900-3c1e-11e9-8efc-a2645b27c8b1.png)

-----

```
Test Environment : 

1. WP 5.1
2. rtMedia 4.5.6
```

**Comment by surajkrsingh** [comment]
@kjnanda @pooja-muchandikar We have discussed with @pranali333 about this issue so right now we don't have such functionality to keep multiple uploader on single page/post.
For this functionality we will look.
CC @pranali333

**Comment by kjnanda** [comment]
Since this is yet to implemented I am removing label `Bug` and making it as an enhancement.

**Comment by kjnanda** [comment]
Closing this issue since this does not seems to be a requirement of providing the multiple uploaders within the same page!
