### ISSUE TITLE
rtMedia Setting -> Export/Import Tab - Export Settings button - is not working in Firefox

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1289]
No action is being performed after clicking on `Export Settings` Button.

As per the scenario, it should download the rtMedia Settings. I found that the request has been sent but the file is not being downloaded. 

Please check this visual. https://goo.gl/fEoWBd

---
```
Test Environment

1. WP Version - 5.1
2. rtMedia Version - 4.5.6(latest)
3. Firefox Version - (65.0.1 (64-bit))

```

**Comment by surajkrsingh** [comment]
PR:-https://github.com/rtMediaWP/rtMedia/pull/1310

**Comment by pooja-muchandikar** [comment]
@surajkrsingh 

Testing is done and export settings button is working on firefox browser now. On click of it rtMedia Settings JSON file is downloaded which is expected. 

```
Test Environment
WordPress: v5.1.1
rtMedia: Code from **pre-release** branch ( v4.5.6 )
BuddyPress: v4.2.0
Cross-browser: Firefox, Chrome and Safari
```

**Comment by kjnanda** [comment]
Tested with dev branch. Added changes are working as expected.

**Comment by kjnanda** [comment]
Tested with master branch. Added changes are working as expected.
