### ISSUE TITLE
Pagination button and pagination text box height is not same.

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1293]
## Theme - 2017

![photo_ _media_ _krupa_ _test](https://user-images.githubusercontent.com/15173772/53634648-bb551680-3c40-11e9-8f96-e242f524eedd.png)

-----

## Theme - 2019

![photo_ _media_ _krupa_ _test](https://user-images.githubusercontent.com/15173772/53634679-d0ca4080-3c40-11e9-8682-ca1ca56051d4.png)

**Comment by surajkrsingh** [comment]
Fix issue of pagination text box height.

**Comment by pooja-muchandikar** [comment]
@surajkrsingh 
```
Test Environment
WordPress: v5.1.1
rtMedia Core: Code from the pre-release branch, v4.5.6
BuddyPress: v4.2.0
Themes: 2012, 2016, 2017 and 2019 
```
Testing is done and below are my findings:
1. The fix added is completely accurate, still, the height of the pagination button and the pagination text box is not same. 
2. After the fix added, `Go to page no.` text alignment got changed. The text was appearing centre-aligned but now it is shown at top aligned with the count box. 

![pagination-fix](https://user-images.githubusercontent.com/41000648/54510941-56eec280-4975-11e9-8a88-e3d185c40abe.png)
##

Check with all the default themes issues is the same.

**Comment by pooja-muchandikar** [comment]
@surajkrsingh 

Can we decrease the padding of `go to num` box?  So that both text and button height looks the same. 

Refer: 
![pagination](https://user-images.githubusercontent.com/41000648/54588043-d64cc680-4a47-11e9-8459-5e2c0f8ae972.jpeg)
##

**Comment by pooja-muchandikar** [comment]
@surajkrsingh 

Testing is done and changes added looks fine now. :heavy_check_mark: 

```
Test Environment
WordPress: v5.1.1
rtMedia Core: Code from **pre-release** branch (v4.5.6)
BuddyPress: v4.2.0
Themes: 2012, 2016, 2017 and 2019
```

**Comment by kjnanda** [comment]
Tested with dev branch. Added changes are working as expected.

**Comment by kjnanda** [comment]
Tested with master branch. Added changes are working as expected.
