### ISSUE TITLE
[BuddyPress Nouveau template] Multiple media upload and privacy drop-down are shown

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1294]
**Steps:**

1. Download the latest stable zip from `https://github.com/rtCamp/rtMedia/`
2. Install  and activate the plugin
3. Goto rtMedia Setting > BuddyPress > Enable the settings for `Allow upload from activity stream`
4. Goto rtMedia Setting > Privacy > Enable the settings for `Allow users to set privacy for their content`
5. Click on `Save Settings` button.
6. Goto Activity page.
7. Click on `text area`
8. Observe that there will be multiple upload button and privacy drop down. The number of upload button and privacy drop down will depend on the number of activities present at that moment. 

> E.g. if 3 activity will be there then 3 uploader button and privacy dropdown will be there.

---

Please refer the below screenshot.
![screenshot-krupa dev rtdemo in-2018 12 19-12-05-25](https://user-images.githubusercontent.com/15173772/50205551-a29dca00-038e-11e9-9d50-2edfad976964.png)

---

**Precondition: BP Nouveau template pack should be enabled.**

----
```
Test Environment 

1. WP 5.1
2. rtMedia 4.5.6
3. BuddyPress 4.2.0

```

**Comment by surajkrsingh** [comment]
@pooja-muchandikar @kjnanda 

I have tested this issue with the given environment test but not able to reproduce it.
Tested with All default and rtdating theme (which has nauveau template support ).

**Comment by kjnanda** [comment]
No more facing this issue

**Comment by patelanuj2612** [comment]
This issue still persists, After little investigation found that , if you open multiple tabs in browser, first tab request all activity using ajax and remaining two tabs retrieve content using cache or something, so no ajax request sent for remaining two tabs. And code that resolve this issue written in ajaxComplete part of code. Since two tabs had no ajax request , ajaxcomplete will not called and it gives this type of output. See below reference code 

```
jQuery(document).ajaxComplete(function(event, xhr, settings) {
    if ('legacy' !== bp_template_pack && bp_template_pack) {
        var get_action = get_parameter('action', settings.data);
        if (('activity_filter' === get_action || 'post_update' === get_action || 'get_single_activity_content' === get_action || 'activity_get_older_updates' === get_action) && 'undefined' !== typeof rtmedia_masonry_layout && 'true' === rtmedia_masonry_layout && 'undefined' !== typeof rtmedia_masonry_layout_activity && 'true' === rtmedia_masonry_layout_activity) {
            setTimeout(function() {
                apply_rtMagnificPopup('.rtmedia-list-media.rtm-gallery-list, .rtmedia-activity-container ul.rtmedia-list, #bp-media-list,.bp-media-sc-list, li.media.album_updated ul,ul.bp-media-list-media, li.activity-item div.activity-content div.activity-inner div.bp_media_content, .rtm-bbp-container, ul.rtm-comment-container');
                rtmedia_activity_masonry();
                rtmedia_activity_stream_comment_media();
            }, 1000);
        } else if (('activity_filter' === get_action || 'post_update' === get_action || 'get_single_activity_content' === get_action || 'activity_get_older_updates' === get_action)) {
            setTimeout(function() {
                apply_rtMagnificPopup('.rtmedia-list-media.rtm-gallery-list, .rtmedia-activity-container ul.rtmedia-list, #bp-media-list,.bp-media-sc-list, li.media.album_updated ul,ul.bp-media-list-media, li.activity-item div.activity-content div.activity-inner div.bp_media_content, .rtm-bbp-container, ul.rtm-comment-container');
                rtmedia_activity_stream_comment_media();
            }, 1000);
        }
    }
});
```

Please help me on this. Thanks
