### ISSUE TITLE
Title attribute is missing for media likes

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtMediaWP/rtMedia#1301]
Like we have title attribute for comment likes, we can have title attribute for media likes as well.

Refer screenshot where we have title attribute for comments like, but for media likes title attribute is not there.
https://drive.google.com/open?id=1VjYqDXte0J7sx9dTzULdYJ6xgGhHo8IU
##

Refer below screenshot of comment like where title attribute is added, similarly we need to add it for media likes.
https://drive.google.com/open?id=10-EJXzAQZfx-LQmDo5zGa0WWcSu-nTGd
##

**Comment by surajkrsingh** [comment]
PR:- https://github.com/rtMediaWP/rtMedia/pull/1302

**Comment by pooja-muchandikar** [comment]
@surajkrsingh 

Tested and changes are done as expected. Title attribute for Media Likes is shown now. :heavy_check_mark:

**Comment by kjnanda** [comment]
Tested with dev branch. Added changes are working as expected.

**Comment by kjnanda** [comment]
Tested with master branch. Added changes are working as expected.
