### ISSUE TITLE
BuddyPress comment issue

### ISSUE THREAD

**Issue by pranali333** [rtMediaWP/rtMedia#1303]
One of our customers is facing this issue. Can you please check this further?

> I have installed updated plugin, now comment nesting is working fine.
> but only admin can comment, rest other user getting error message on comment. as
> You have posted an inappropriate word

https://wordpress.org/support/topic/buddypress-activity-commenting-make-new-post/#post-11307458

Thanks,

**Comment by pooja-muchandikar** [comment]
@kjnanda 
I have checked with latest version of rtMedia and BP, created different users in site with different roles and able to comment. Checked on Activity page, Comment on Media lightbox and Comment on Group activity and Group media. And its working as expected.

**Comment by kjnanda** [comment]
Not able to reproduce this issue
