### ISSUE TITLE
Default settings of Add-ons isn't affecting in front end until the user explicitly clicks on Save Settings button in rtMedia settings.

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtMediaWP/rtMedia#1304]
This issue persists in following add-ons.
1. rtMedia Favlist
2. rtMedia Playlist
3. rtMedia Likes

Refer to the visual of an issue with respect to rtMedia fav list add-on, similar issue exists with other add-on as well: https://drive.google.com/file/d/1UJJMFQIXW3vrpzPC9qk5k-uG5T3lOqk7/view

**Comment by kanumalivad** [comment]
@pooja-muchandikar 
I solved this issue for rtmedia favlist (PR:- https://github.com/rtCamp/rtmedia-favorites/pull/28 )
In rtmedia Playlist this issues is no longer exists, But in rtmedia Likes It is still there so fix is in respective add on not in core. So i suggest close this issue from here and open new issue in rtmedia likes.

**Comment by pooja-muchandikar** [comment]
@kanumalivad 

Checked Fav list add-on settings and it is working now. Also, found that playlist add-on there is no issue with the save settings.

I've created a separate issue for likes add-on. **Issue link:** https://github.com/rtCamp/rtmedia-likes/issues/46

Closing this issue, as the issue is in likes add-on and the fix will be added in likes add-on itself. 

cc: @kjnanda @pranali333
