### ISSUE TITLE
Group Activity media are not shown in Group Media tab with BuddyPress Nouveau Template.

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtMediaWP/rtMedia#1319]
**Steps to Reproduce**

1. Set BuddyPress template to Nouveau and Save settings
2. Go to Groups and create a group
3. Go to group activity and upload any media in the group activity
4. Observe that media uploaded through group activity are not reflecting in the group media tab.
5. Now, go to profile media tab and observe that media uploaded through group activity are reflecting in the profile media tab which shouldn't be.

**_Media uploaded through group activity should reflect in the group media tab, not in the profile media tab. This issue exists with the nouveau template. With BuddyPress legacy template it is working as expected._**

**Refer Visual:** https://drive.google.com/open?id=1OtUZFW6nuhIbxJkGKGXkZUKC4ZiZA2og
##

```
Test Environment
WordPress: 5.1.1
rtMedia: 4.5.6
BuddyPress: 4.2.0 ( Nouveau Template )
```
cc: @kjnanda

**Comment by pooja-muchandikar** [comment]
@kanumalivad 

Testing is done with the following test environment and fix added works as expected. 

```
Test Environment
rtMedia Core: v4.5.6 ( code from **pre-release** branch )
BuddyPress: v4.2.0 ( nouveau and legacy template )
```

**Comment by kjnanda** [comment]
Tested with dev branch. Added changes are working as expected.

**Comment by kjnanda** [comment]
Tested with master branch. Added changes are working as expected.
