### ISSUE TITLE
Shows Notices from rtMedia on Favlist page when Buddpyress Nouveau template is active

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1320]
![Unnamed image (13)](https://user-images.githubusercontent.com/15173772/54978323-0525e800-4fc6-11e9-8052-eb6bf4ef4e3b.png)

-----

```
Test Environment 

WP - 5.1.1
rtMedia - 4.5.6
Buddypress - 4.2.0 - Nouveau Template 
rtMedia favlist - 1.2.6

```

**Comment by kanumalivad** [comment]
This issue has been fixed in rtmedia-favorite add on.
PR ref : - https://github.com/rtCamp/rtmedia-favorites/pull/27

**Comment by kjnanda** [comment]
Clsoing this issue as the fix is added in rtMedia favlist add-on
