### ISSUE TITLE
Shows PHP warning on uploading media from Media Page.

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtMediaWP/rtMedia#1322]
```
Test Environment
WordPress: v5.1.1
rtMedia Core: v4.5.6
BuddyPress: v4.2.0
Themes: Default theme 2012, 2016 and 2019
```

**Steps to Reproduce**
1. Activate rtMedia and BuddyPress plugin
2. Set debug.log true
3. Navigate to Media tab and upload any media
4. Media gets uploaded successfully
5. Now, check the debug.log file PHP warning is shown as soon as media is uploaded.

**Note: Checked media upload through activity page and on uploading media from activity page no warning were shown but from media page warning is shown. Media page, group media page etc.**

Refer issue visual: https://drive.google.com/open?id=1hjXAWfc3w31grLpxGXXARJtuVWlY56iH

cc: @kjnanda

**Comment by pooja-muchandikar** [comment]
@kanumalivad 

Tested issue with the following test environment and the added fix works. 

```
Test Environment
rtMedia Core: v4.5.6 ( code from **pre-release** branch )
BuddyPress: v4.2.0 ( nouveau and legacy template )
Themes: Default themes 2012, 2016, 2017 and 2019 
```

**Comment by kjnanda** [comment]
Tested with dev branch. Added changes are working as expected.

**Comment by kjnanda** [comment]
Tested with master branch and I don't see any such Warning with added changes.
