### ISSUE TITLE
[Frontend] PHP Deprecated Error while changing or removing the thumbnail for music media type

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1325]
Please check this visual - https://goo.gl/xR5QVK

-----

```
Test Environment 

1. Wordpress 5.1.1
2. Buddypress 4.2.0
3. rtMedia 4.5.6
4. Custom thumbnail add-on - Code from pre-release branch (commit id - bb26064c1dd356aa1d9735ef14f5209e4d696785 )
```

**Comment by surajkrsingh** [comment]
@kjnanda @pooja-muchandikar 

This issue is also the same as https://github.com/rtCamp/rtMedia/issues/265
Already solved - https://github.com/rtCamp/rtMedia/issues/265#issuecomment-489189214

**Comment by kjnanda** [comment]
@surajkrsingh I am still facing the same error. Kindly check this.

**Comment by dharmin** [comment]
I've checked with this issue on `pre-release` branch, and the issue is not getting reproduced on my side.

**Comment by kjnanda** [comment]
@dharmin I am still facing this issue at my end.

> [06-Jun-2019 08:49:42 UTC] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; getid3_writetags has a deprecated constructor in /Applications/MAMP/htdocs/rtmedia-4.5.7/wp-content/plugins/rtMedia/lib/getid3/write.php on line 48
> [06-Jun-2019 08:49:42 UTC] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; getid3_write_id3v2 has a deprecated constructor in /Applications/MAMP/htdocs/rtmedia-4.5.7/wp-content/plugins/rtMedia/lib/getid3/write.id3v2.php on line 19
> [06-Jun-2019 08:49:42 UTC] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; getid3_write_id3v1 has a deprecated constructor in /Applications/MAMP/htdocs/rtmedia-4.5.7/wp-content/plugins/rtMedia/lib/getid3/write.id3v1.php on line 19
> [06-Jun-2019 08:49:42 UTC] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; getid3_write_apetag has a deprecated constructor in /Applications/MAMP/htdocs/rtmedia-4.5.7/wp-content/plugins/rtMedia/lib/getid3/write.apetag.php on line 20
> [06-Jun-2019 08:49:42 UTC] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; getid3_write_lyrics3 has a deprecated constructor in /Applications/MAMP/htdocs/rtmedia-4.5.7/wp-content/plugins/rtMedia/lib/getid3/write.lyrics3.php on line 18
> 

-----



**Test environment**

1. WP 5.2.1
2. rtMedia - Code from pre-release branch
3. rtMedia set custom thumbnail add-on - latest code from master branch

**Comment by kjnanda** [comment]
@thrijith I have checked the code from `update/getid3-lib` branch and facing the following Warning.

> [06-Jun-2019 11:51:21 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /Applications/MAMP/htdocs/rtmedia-4.5.7/wp-content/plugins/rtMedia-update-getid3-lib/app/main/controllers/media/RTMediaMedia.php on line 715

**Comment by kjnanda** [comment]
@dharmin @surajkrsingh I tested this with the latest code from the pre-release branch(09985189fb3287c48dad3b8d44eb47ac99ce55f4) and I don't see any of the notices or warnings mentioned above.

CC @thrijith

**Comment by kjnanda** [comment]
Tested with dev branch. Added changes are working as expected. I don't see any more errors.

**Comment by kjnanda** [comment]
Tested with master branch. Added changes are working as expected. I don't see any more errors.
