### ISSUE TITLE
Delete FavList -> Styling looks different than Edit Favlist. It Should be consistent. 

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtMediaWP/rtMedia#1333]
```
Test Environment
rtMedia Core: v4.5.6
BuddyPress: v4.2.0 ( nouveau and legacy template )
rtMedia Favorites add-on: v1.2.7
```

Refer the below screenshot below edit and delete icons styling are not consistent.

![54979446-2b995280-4fc9-11e9-91c3-29f73ce01d43](https://user-images.githubusercontent.com/41000648/56496774-7189fd80-6518-11e9-9d7c-24e50ae3c56a.png)

**Comment by kjnanda** [comment]
Added changes are working as expected. Testing is done with `pre-release branch`

**Comment by kjnanda** [comment]
Tested with dev branch. Added changes are working as expected.

**Comment by kjnanda** [comment]
Tested with master branch. Added changes are working as expected.
