### ISSUE TITLE
Username's auto suggestion is not working while tagging them from lightbox

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1339]
We can consider two main scenarios as listed below.

1. When the user tries to tag the friend user from the lightbox. ❌ 
1. When the user tries to tag the friend user on a single media page ✅ 

Please check this visual. I have shown both scenarios - https://drive.google.com/file/d/1R3PqNoR_CohCT48C0YF-9d3x0TGHSxvb/view

------------
```
Test Environment Used

1. rtMedia 4.5.6
2. Buddypress 4.3.0
3. WP 5.2

```

**Comment by kjnanda** [comment]
@dharmin This is not yet working for me. Kindly check this.

**Comment by dharmin** [comment]
PR: https://github.com/rtMediaWP/rtMedia/pull/1348 is merged now.

**Comment by kjnanda** [comment]
@dharmin I have cross verified this and this looks good to me. 

Tested with the code from pre-release branch

**Comment by kjnanda** [comment]
Tested with dev branch. Added changes are working as expected.

**Comment by kjnanda** [comment]
Tested with master branch. Added changes are working as expected.
