### ISSUE TITLE
Issue with BuddyPress Legacy template - Media name is not completely visible on activity Page

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1373]
Please check this snapshot. 

![Screenshot of krupa – rtmedia-stable](https://user-images.githubusercontent.com/15173772/59334651-99c3fa80-8d18-11e9-8762-b9e2a194ad67.jpg)

----

Proposed Solution : 

1. Disabling this css property `overflow: hidden;` 
2. Decrease the font size

![Screenshot (11)](https://user-images.githubusercontent.com/15173772/59337839-f0ccce00-8d1e-11e9-9d5f-d0117dff2fc2.jpg)

**Comment by surajkrsingh** [comment]
PR:-https://github.com/rtMediaWP/rtMedia/pull/1382
Issue description:- Media title is getting hide in legacy template.
Solution :- Unset  `overflow:hidden`

**Comment by kjnanda** [comment]
@surajkrsingh Changes are not reflecting at my end. Could you please check once?

**Comment by kjnanda** [comment]
This looks good and tested with `pre-release` branch. ✅

**Comment by surajkrsingh** [comment]
@kjnanda @dharmin 
This issue was not completely solved with given PR https://github.com/rtMediaWP/rtMedia/pull/1390 even it breaking the activity comment box in theme 2019 and 2014.

**Comment by kjnanda** [comment]
@surajkrsingh Added changes are working as expected with given PR

**Comment by kjnanda** [comment]
This is working as expected and tested with `pre-release` branch. ✅

**Comment by kjnanda** [comment]
This is working as expected and tested with `dev` branch. ✅

**Comment by kjnanda** [comment]
This is working as expected and tested with `master` branch. ✅

**Comment by kjnanda** [comment]
Closing this issue as this has been fixed and release in - V 4.5.8
