### ISSUE TITLE
rtmedia_activity_content_html filter not working

### ISSUE THREAD

**Issue by contemplate** [rtMediaWP/rtMedia#1379]
We have rtMedia plugin that came with the Kleo theme. I'm trying to switch the order of the buddypress activity comment text with the media list. I'm using the following snippet and have tried adding it functions.php as well as bp-custom.php

Neither works!  

Anyone else having this issue?

https://rtmedia.io/docs/developers/hooks/rtmedia-activity-content-html/

add_filter( 'rtmedia_activity_content_html', 'custom_activity_content_html', 10, 3 );
function custom_activity_content_html( $activity_content, $activity_text, $media_list ) {
   return $media_list . $activity_text;
}

**Comment by kjnanda** [comment]
Hi there,

I checked the same thing at my end and found that this snippet works as expected. I added the code in the `(kleo)theme's function.php` file.

-----

Please check this visual. 

![rtmedia_filter_kleo_theme](https://user-images.githubusercontent.com/15173772/59658899-94f0c200-91c2-11e9-8117-f3291d55d260.gif)

-----

**PS - The snippet will not affect the previously posted activity.** 

If you have any further query, please open a new ticket on our support channel – https://rtmedia.io/support/

Thanks,

Krupa Nanda
