### ISSUE TITLE
Not able to upload file more than 8MB size

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1387]
@surajkrsingh Please check why it does not allow to upload the media more than 8MB. Though values are set to 32MB

![Unnamed image (11)](https://user-images.githubusercontent.com/15173772/59835159-d4f0aa00-9366-11e9-83a4-9d2df9823d08.png)

![Screenshot (12)](https://user-images.githubusercontent.com/15173772/59835172-db7f2180-9366-11e9-8ab1-ef946f69bfda.jpg)

**Comment by surajkrsingh** [comment]
@kjnanda
 Here `post_max_size` is less then `upload_max_filesize`so it is not able to upload the file more then  `post_max_size` so we have to increase the size of `post_max_size` at least equal to the `upload_max_filesize` .

 Solution (update php.ini parameter):- 
`post_max_size = 32`
`upload_max_filesize = 32`

**Comment by surajkrsingh** [comment]
I am closing this issue because it is not an issue. Just we have to set up the parameter in php.ini file.

**Comment by surajkrsingh** [comment]
I am closing this issue because it is not an issue. Just we have to set up the parameter in php.ini file.
