### ISSUE TITLE
Add new class to rtmedia activity list (<ul class="rtm-activity-media-list"></ul>), depending on media type

### ISSUE THREAD

**Issue by razor2016** [rtMediaWP/rtMedia#1389]
Hi there, 

Can you add a new class to the activity media list? Currently, it comes with .rtmedia-list, .rtm-activity-media-list and .rtmedia-activity-media-length-3 classes. It would be really great if you could add one more class depending on the media type. 

For example, 

1. .rtmedia-photo-list for photos only activity
2. .rtmedia-video-list for video only activity
3. .rtmedia-audio-list for video only activity
4. .rtmedia-mixed-list for mixed medias. Lets say user posted 2 photos and 1 audio. 

The reason I am posting this is because if we have those classes, I can style the activity in a better way. Lets say I have photos only activity, then I will display them as small thumbnails. On the other hand, If I have mixed medias in the activity, I will give them full width. 

Thanks

**Comment by kjnanda** [comment]
Hi @razor2016 

I checked with my team and confirmed that we can introduce this change during our future release.

Meanwhile, if you want to style based on the media type you can use `media-type-photo` `media-type-video` classes. But you won’t be able to style one whole activity that contains a specific media type. 

Thanks,

Krupa Nanda

**Comment by razor2016** [comment]
That's cool. Yeah I saw those classes. Thanks

**Comment by thrijith** [comment]
@kjnanda a PR that adds support the request has been merged into `pre-release` please test and verify if it works as expected.

It will add, any one of the following classes to the `ul`, based on media type.

- rtm-activity-video-list
- rtm-activity-music-list
- rtm-activity-photo-list
- rtm-activity-mixed-list

**Comment by kjnanda** [comment]
@thrijith 

This is working as expected and tested with `pre-release` branch. ✅

**Comment by pooja-muchandikar** [comment]
Tested with pre-release branch and its working as expected. 
Tested with the given classes and classes are reflecting as expected.
