### ISSUE TITLE
Drop down file uploader shows incorrect file size limit tool tip.

### ISSUE THREAD

**Issue by surajkrsingh** [rtMediaWP/rtMedia#1395]
Drop-down file uploader on media page shows incorrect file size limit on tool tip message.

Screenshots
![screenshot-1](https://user-images.githubusercontent.com/19591301/60179644-c0675280-983b-11e9-99a4-956400dff287.jpg)
***
![screenshot-2](https://user-images.githubusercontent.com/19591301/60179655-c5c49d00-983b-11e9-9176-a99f83864b35.jpg)

Note :- In both the tool tip file size limit should be same.

**Comment by surajkrsingh** [comment]
@kjnanda 
I have test the and debug the code and found from above:- 
File size limit shows on uploader tool tip is incorrect.

**Comment by surajkrsingh** [comment]
PR:- https://github.com/rtMediaWP/rtMedia/pull/1396

**Comment by kjnanda** [comment]
Closing this issue as this has been fixed and release in - V 4.5.8
