### ISSUE TITLE
Add like icon for comment like

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1401]
We have added like icon for media likes but it is not there for comment like.

![rtMedia_Demo_Site___This_is_a_demo_site_for_rtMedia_and_premium_add-ons](https://user-images.githubusercontent.com/15173772/60651185-4cdccb00-9e63-11e9-8820-2c9ba994d10f.png)

-----

```
Test Environment

1. WP V5.2.2
2. rtMedia V4.5.7

```

**Comment by surajkrsingh** [comment]
I am closing this issue because this issue in like add-on since the fix will be added there.
