### ISSUE TITLE
[PHP Warnings] shows on support page

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1404]
Please refer to this snapshot.

![Support_‹_krupa-rtmedia-plugins_dev2_rt_gw_—_WordPress](https://user-images.githubusercontent.com/15173772/61104869-74e8b180-a495-11e9-8a69-5593ab5478bb.png)

----

Goto Dashboard > rtMedia Settings > Support - Shows the php warnings here

**Comment by kjnanda** [comment]
If you are unable to replicate warnings on your test environment, please check this on demo site.

**Comment by dishitpala** [comment]
@kjnanda 
Issue: Used `count` function on a string to remove the file extension ( .php )
Solution: Use `str_replace` to remove `.php` extention

**Comment by Dhavalk15** [comment]
/app/helper/RTMediaSupport.php b/app/helper/RTMediaSupport.php
Line no:254
$rt_to_dir_paths	= RTMediaTemplate::locate_template( substr( $sub_file, 0, ( strlen( $sub_file ) - 4 ) ) );

**Comment by dishitpala** [comment]
@kjnanda This issue has been fixed on `pre-release` branch

**Comment by Dhavalk15** [comment]
I want to contribute can you tell the process of it ?

**Comment by kjnanda** [comment]
@dishitpala The reported warnings are not showing but I see some other warnings. Please check this screenshot.

![Support_‹_test_—_WordPress](https://user-images.githubusercontent.com/15173772/69696450-b9ec4800-1105-11ea-9a4a-47a90190158a.png)

**Comment by dishitpala** [comment]
@kjnanda I am not able to see any of the above warnings in my setup.

**Comment by kjnanda** [comment]
@dishitpala https://github.com/rtMediaWP/rtMedia/issues/1404#issuecomment-558936947 this is only happening on local setup created with `MAMP` but was not able to such warning on dev server site.

**Comment by kjnanda** [comment]
Hi @dhavalkasavala,

My sincere apologies for the slow reply!

Thank you so much for showing the interest to contribute to our plugin!

**You can follow this process to contribute.**

1. If you found something which is not working as expected then you can create an issue. 
   https://github.com/rtMediaWP/rtMedia/issues/new
2. If you want to work on any existing issue then left a comment on the issue. After we assign that to you, you can start working on it.
     * Once you add the fix, raise the PR from your forked repo to the `pre-release` branch of rtMedia.
     * After then our team will review your PR and they will add feedback on PR if any
     * Once you address the feedback, the PR will get approved
     * If everything looks good then we will merge the PR

Please let us know if you have any queries regarding contribution.

Regards,
Krupa

**Comment by pooja-muchandikar** [comment]
@dishitpala 

Checked with `pre-release` branch and didn't face any warnings. 

cc: @kjnanda

**Comment by pooja-muchandikar** [comment]
Release with 4.5.10 version.
