### ISSUE TITLE
[Customer Query] Unable to post media and hyperlink in activity comment

### ISSUE THREAD

**Issue by thrijith** [rtMediaWP/rtMedia#1422]
Ref: https://wordpress.org/support/topic/you-have-posted-to-many-links-comments/#post-11844071

**Comment by thrijith** [comment]
@kjnanda The issue should be fixed now, please test `pre-release` branch and verify if it works as expected. Thanks.

**Comment by kjnanda** [comment]
@thrijith 
This is working as expected and tested with `pre-release` branch. ✅

Tested this scenario on below pages.

1. Sitewide Activity Page ✅ 
2. User's activity Page ✅ 
3. Group - Sitewide Activity Page ✅ 
4. Group - User's activity Page ✅

**Comment by pooja-muchandikar** [comment]
Tested issue with pre-release branch and its working fine.

**Comment by pooja-muchandikar** [comment]
https://drive.google.com/file/d/1RDDodBoOR1UP7RUY3RglRLLpVBCAk4W8/view

Please refer to the above visual, facing issue while commenting. Checked in pre-release and develop both branches.

**Comment by pooja-muchandikar** [comment]
Tested with the master branch and works as expected.
