### ISSUE TITLE
Activity medias hide inside Read more link if the activity text is long

### ISSUE THREAD

**Issue by razor2016** [rtMediaWP/rtMedia#1424]
Hi there,

First of all, thank you guys for being so active with the plugin. It's a great one.

Recently, I came across an issue (not an issue actually) in which I noticed if you have a long activity then the medias hide inside the read more link. You have to click the read more link to expand the activity to see the medias. Please see the attachments. 

![Capture](https://user-images.githubusercontent.com/20941700/63796499-fdc58a80-c927-11e9-9532-ff6f48f09d0b.PNG)
![Capture1](https://user-images.githubusercontent.com/20941700/63796501-fe5e2100-c927-11e9-8f37-587650110a64.PNG)

I think medias are the most important things in the activity so regardless of activity length they should be visible. What you guys think?

Maybe, instead of having medias inside `.activity-inner` class, having them between `.activity-inner` and `.activity-meta` would solve this. (a direct child `.activity-content`?)

Looking forward to hearing from you.

Regards

**Comment by kjnanda** [comment]
Hi @razor2016 

> First of all, thank you guys for being so active with the plugin. It's a great one.

Thank you very much for liking our work. :)

Regarding the query you posted, I understand your concern. This is the default behavior. But if you want to override this then you can use one filter to show the media first and then content.

Please check out this link - https://rtmedia.io/docs/developers/hooks/rtmedia-activity-content-html/

Apply the filter mentioned in the above link in your theme's `function.php` file and the output would be something like as shown in below.

-----

**1. Before you click on Read More link -** 

![Fullscreen_8_28_19__9_54_AM](https://user-images.githubusercontent.com/15173772/63825852-f333e100-c979-11e9-83b3-a0d2e80c9057.png)


**2. After you click on Read More link -** 

![Activity_–_krupa_nanda_–_krupa-rtmedia-plugins_dev2_rt_gw](https://user-images.githubusercontent.com/15173772/63825887-237b7f80-c97a-11e9-85ef-ef6507655366.png)

-----

Please let me know if this is what you are looking for.

Thanks,

Krupa

**Comment by razor2016** [comment]
@kjnanda 

Thank you for sharing the function. I think that would work for me.

Also, I'm thinking there might be another way to do this without changing the order of the contents by making the buddypress excerpt longer and truncate the `rtmedia-activity-text` with jquery. A read more button will then expand truncated text. What do you think?

I will try both of them and see which one works for me.

Thank you so much for your plugin and support.

Cheers

**Comment by kjnanda** [comment]
Hi @razor2016 

> I'm thinking there might be another way to do this without changing the order of the contents by making the BuddyPress excerpt longer and truncate the .rtmedia-activity-text with jquery. A read more button will then expand the truncated text. What do you think?

Please let us know if that works for you. 

> Thank you so much for your plugin and support.

We are glad that you liked our plugin and support. 

Could you please give us your valuable feedback on rtMedia as a plugin and how it has helped you? 

It will help us serve you better. 

Here is the link - https://wordpress.org/support/plugin/buddypress-media/reviews/?filter=5

Also, I am closing this ticket since this is not the issue actually. 

You can also create a ticket on our support page - http://rtmedia.io/support
Please feel free to open a new ticket in case you find something which is not working.

Thanks,

Krupa
