### ISSUE TITLE
[Customer Query] Issue with accessing the media attached as a comment when privacy kept off

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1430]
If members post a comment with an attachment(from the activity) then the only administrator can see it in a lightbox. Logged in users and a guest gets the following error…

```Sorry !! There’s no media found for the request !```

I am able to replicate this issue at my end but temp workaround I could find is to enable the privacy and then issue will no more exist! 

Please refer to this attachment to understand the issue. https://drive.google.com/file/d/1FgVin0RnXn6Hittyk9yMMcRl0Y_W188M/view

----

https://wordpress.org/support/topic/4-9-8-only-administrator-can-see-lightbox-content/

**Comment by vermadarsh** [comment]
Hi @pooja-muchandikar 

I tested this with the following environment details:
rtMedia: v4.5.11
BuddyPress: v5.1.2
WordPress: v5.3.2

I'm unable to replicate this issue, it seems everything works correctly.

**Comment by pooja-muchandikar** [comment]
I have cross-checked this issue with following test environment and couldn't able to reproduce it. Able to access media attached as a comment with Privacy enabled/disabled in both scenarios.

```
Test Environment
WordPress: v5.3.2
rtMedia: v4.6.0
BuddyPress: v5.1.2
```

Hence, closing this issue.
