### ISSUE TITLE
Issue list with BuddyPress 5.0.0

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtMediaWP/rtMedia#1432]
- [x] 1. Post update button on Activity page is not visible with BP 5.0.0 with Nouveau template. 
```
Test Environment
WordPress: v5.2.3
rtMedia: v4.5.8
BuddyPress: 5.0.0 ( Nouveau Template )
Theme: 2019, 2017
```

**Comment by dishitpala** [comment]
_1. Post update button on Activity page is not visible with BP 5.0.0 with Nouveau template._

@kjnanda / @pooja-muchandikar 
We have `Enable Direct Upload` Feature in rtmedia
So if this feature is enabled then the `Post Update` button should be visible or not?

**Comment by kjnanda** [comment]
It should be visible but it will not need to be clicked on.

**Comment by dishitpala** [comment]
@kjnanda I have created PR for
- Post update button on Activity page is not visible with BP 5.0.0 with Nouveau template.

While testing I faced some other CSS issues as well ( All buttons are not indented properly )
![Activity – admin – rtmedia (2)](https://user-images.githubusercontent.com/25063903/66629249-d1877400-ec1e-11e9-95b3-f4cd19f2fd50.png)

Above image testing environment 
```
BuddyPress: 3.0.0
Theme: TwentyNineteen
Rtmedia: 4.5.8
```
Please can you check this at your end

**Comment by kjnanda** [comment]
@dishitpala We can skip CSS part as of now. `Post Update` should be there which is in priority.

@thrijith will that be fine?

**Comment by kjnanda** [comment]
This is working as expected and tested with the `pre-release` branch. ✅

**Comment by pooja-muchandikar** [comment]
@dharmin @thrijith 
Tested with the following test environment
```
WP: v5.2.4
BP: v5.0.0
rtMedia: v4.5.8 pre-release branch
```

Tested this scenario with the below pages: 
Sitewide Activity
User's activity
Group - Activity 

And it works fine.

**Comment by pooja-muchandikar** [comment]
Tested with develop branch and its working fine. 
```
WP: v5.2.4
BP: v5.0.0
rtMedia: v4.5.9 develop branch
```

**Comment by pooja-muchandikar** [comment]
Tested with the master branch and its working fine.
