### ISSUE TITLE
[Dashboard] Correct redirection on hire us page in dashboard

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1447]
Currently, it is redirecting to https://rtmedia.io/contact which is not correct. 

We need to redirect it to - https://rtmedia.io/enterprise-plan/

------

Steps:

1. Goto rtMedia settings in Dashboard
2. Click on Hire us tab
3. Check the link on the `Contact Us` button which needs to be updated.

**Comment by kjnanda** [comment]
This is working as expected and tested with the `pre-release` branch. ✅

**Comment by pooja-muchandikar** [comment]
Correct redirection link is added :heavy_check_mark:

**Comment by pooja-muchandikar** [comment]
Release with 4.5.10 version.
