### ISSUE TITLE
Incorrect css class on the error message of media update.

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1477]
HTML in media_update_success_error() action have incorrect css class rtmedia-error instead of rtmedia-warning.

PR: https://github.com/rtMediaWP/rtMedia/pull/1611

**Comment by kjnanda** [comment]
@SID177 What output am I supposed to expect here? Can you provide me a visual of before fix and after fix?

**Comment by SID177** [comment]
@kjnanda 
Before adding fix
![Screenshot 2020-04-20 at 11 29 35 AM](https://user-images.githubusercontent.com/23107546/79718744-6b308c00-82fa-11ea-86ed-8fa29d66513b.png)

After adding fix
![Screenshot 2020-04-20 at 11 30 12 AM](https://user-images.githubusercontent.com/23107546/79718757-708dd680-82fa-11ea-8fea-b5d7f236db1b.png)

**Comment by kjnanda** [comment]
@SID177 Please check the below screenshot.

![Media_–_ADMINUSER_–_beta_release_testing](https://user-images.githubusercontent.com/15173772/79748372-f1fd5d00-832a-11ea-8d70-cd613a7ebb2f.png)

I am seeing this message twice upon saving the media after changes. 

Also, I am not able to generate the error you have shown in the screenshot shared by you!

**Comment by kjnanda** [comment]
@SID177 I am not able to understand this issue. 

With this code `if ( false == $state ) {` I see the below screenshot! 

----

![Media_–_ADMINUSER_–_beta_release_testing](https://user-images.githubusercontent.com/15173772/79843384-d3a16b00-83d7-11ea-8041-faef7e652b43.png)

---
It will be really great if you can further debug this issue and can point me in the right direction.

**Comment by SID177** [comment]
@kjnanda I've fixed the media update message showing twice issue in PR - https://github.com/rtMediaWP/rtMedia/pull/1620
The code is merged in `pre-release`

**Comment by SID177** [comment]
@kjnanda Make sure you have latest `pre-release` branch. Try hard refreshing the browser. If it doesn't work then inspect the error message and check whether the div has `rtmedia-warning media-edit-messge` class on it.
If it has `rtmedia-error media-edit-messge` class on then I think you don't have the latest code.

Check `app/main/controllers/template/RTMediaTemplate.php` file's 475 line. The div should have `rtmedia-warning media-edit-messge` class if it's latest code.

**Comment by kjnanda** [comment]
@SID177 This is working fine 👍

**Comment by kjnanda** [comment]
This is working as expected and tested with `dev` branch. ✅

**Comment by kjnanda** [comment]
Closing this issue as this has been fixed and release in - V4.6.2
