### ISSUE TITLE
Correct the spelling mistake in variable name.

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1496]
It may be possible that, same variable of that class might have used in add-ons as well. So please verify that and list down add-ons in which it has been used and then find the best way to fix in main plugin and add-ons.

--------

Have to check in other add-ons if they using this class as base. So other class might be using this variable.

_Originally posted by @vaishaliagola27 in https://github.com/rtMediaWP/rtMedia/pull/1480_

**Comment by thrijith** [comment]
The functions and variables can be used by other plugins that we are not aware of, to stay on the safe side let's not rename `public` and `protected` functions and properties.

**Comment by pooja-muchandikar** [comment]
Closing this issue for now as we are not going to rename any variables https://github.com/rtMediaWP/rtMedia/issues/1496#issuecomment-577556426
