### ISSUE TITLE
Issue with Default albums

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtMediaWP/rtMedia#1531]
Newly created default albums are shown in the albums drop-down while uploading media irrespective of album preselected.

1. Active default album add-on
2. Select Wall posts as `preselected album`
3. Created new album
4. Go to frotnend media page
5. Click on upload, observe that album selection drop-down shows the default album as the newly created album not the preselected album. Ideally it should show preselected album. 

Refer -> https://drive.google.com/file/d/1EBbn9egsSwu4sj08888QZT8dknnI4ssO/view

Where as refer to the below visual in which it is working as expected. 
https://drive.google.com/file/d/1miEFwSoSaiy-__SwUkwLv0WJiecMF6Kh/view 

```
Test Environment
WordPress: v5.3.2
rtMedia: v4.5.11
BuddyPress: v5.1.2
Default Albums: v1.1.3 and final zip for 1.1.4 release
```
With above test environment in one of the site it is working but in another it is not. Need to debug this issue.

**Comment by dishitpala** [comment]
File to refer while solving the issue:
`buddypress-media/app/main/controllers/upload/RTMediaUploadView.php` -> `render` function

**Comment by vermadarsh** [comment]
@pooja-muchandikar 
I'm unable to replicate this issue.
Working screencast: https://www.loom.com/share/3734a76fa75247cbbbd3e4108624b3e5
Password for the screencast: `goodwork`

**Comment by pooja-muchandikar** [comment]
```
Test Environment
WordPress: v5.3.2
rtMedia: v4.6.0
BuddyPress: v5.1.2
Default Albums: v1.1.4 stable version
```

Tested this issue with above test environment and the issue is not reproducible. Closing this issue for now. Will re-open if required.
