### ISSUE TITLE
Profile media tab loads BP Legacy template instead of Nouveau

### ISSUE THREAD

**Issue by jeffreyblueprint** [rtMediaWP/rtMedia#1543]
I have similar issue than [this thread](https://github.com/rtMediaWP/rtMedia/issues/1237), where BP switches to Legacy template when on the Media tab in BP Nouveau.

Running all latest versions:
Wordpress 5.3.2
Buddypress 5.1.2
rtMedia 4.5.11
Theme: Hestia (same issue with Twenty themes)

**Comment by pooja-muchandikar** [comment]
Hello Jeffrey,

My team will look into it and I will get back to you asap.

**Comment by pooja-muchandikar** [comment]
Hi @jeffreyblueprint 

We were able to reproduce the issue. We will fix this issue in our next release. 

Meanwhile,  I would like to request you to open a new support ticket on our support channel - https://rtmedia.io/support. We will further communicate over a support channel. Please draft your query and issue you are facing. 

Have a nice day!

Regards,
Pooja

**Comment by pooja-muchandikar** [comment]
@SID177 

Tested with `develop` branch and the fix added works fine with nouveau template. Profile media tabs now loads BP templates accordingly.

**Comment by pooja-muchandikar** [comment]
Tested with `master` branch and the fix added works as expected.

**Comment by pooja-muchandikar** [comment]
Released with `v4.6.0`

**Comment by pooja-muchandikar** [comment]
@jeffreyblueprint 

We have fixed the issue and released please check. 

Regards,
Pooja
