### ISSUE TITLE
Another deprecated unparenthezised conditional statement - RtMediaInteraction.php line 286

### ISSUE THREAD

**Issue by bbuclin** [rtMediaWP/rtMedia#1551]
Hi,

getting my debug.log file filled up with following message:

`[09-Feb-2020 14:38:45 UTC] PHP Deprecated:  Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in .../wp-content/plugins/buddypress-media/app/main/interactions/RTMediaInteraction.php on line 286`

Original line reads:
`		$s        = empty( $_SERVER['HTTPS'] ) ? '' : ( 'on' === $_SERVER['HTTPS'] ) ? 's' : '';
`
Simple correction is to wrap the second test in parenthesis:
`		$s        = empty( $_SERVER['HTTPS'] ) ? '' : ( ('on' === $_SERVER['HTTPS'] ) ? 's' : '');`

**Comment by kjnanda** [comment]
Hi @bbuclin 👋 

I am closing this issue as this has been released in V4.6.0
