### ISSUE TITLE
Same ID is being used for every terms condition checkbox

### ISSUE THREAD

**Issue by SID177** [rtMediaWP/rtMedia#1587]
Visual - https://drive.google.com/file/d/1PgfWE_AMxiv9tykLa1Sg_30ahOMSBB4t/view?usp=sharing
I think best way to fix this is by changing ID of every terms condition checkbox based on it's location.
Checked this issue in `develop`

**Comment by SID177** [comment]
>I think best way to fix this is by changing ID of every terms condition checkbox based on it's location.

By fixing this, we'll also fix https://user-images.githubusercontent.com/15173772/77053177-f238ce80-69f3-11ea-8ca8-4689f90edeec.png of  https://github.com/rtMediaWP/rtMedia/issues/1565#issuecomment-601084530

**Comment by kjnanda** [comment]
@SID177 Please start working on this issue. Please let me know if you are going to change the id of terms of condition checkbox in rtmedia core itself. I will have to change the same in my automation script Variables.

**Comment by SID177** [comment]
@kjnanda I've changed ID of terms and condition checkbox in sidebar widget addon. If you need to change any automation script the new ID is `rtmedia_widget_upload_terms_conditions`

**Comment by kjnanda** [comment]
@SID177 This looks good to me. 

Tested this on the activity page, media page for profile and group both. Also, checked with the shortcode.

**Comment by kjnanda** [comment]
This is working as expected and tested with `dev` branch. ✅

**Comment by kjnanda** [comment]
Closing this issue as this has been fixed and release in - V4.6.1
