### ISSUE TITLE
Round of testing with pre-release branch of rtMedia core with other add-ons

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1593]
- [x] **1. Facing the issue while posting the media/doc in bbPress forum. I am able to upload the media but first, it takes me to this below page and then going back it shows that media is posted and also, uploaded media is not removed from the uploader panel.**

----

![localhost_beta-testing_groups_test-grp_forum_topic_first-topic__post-187](https://user-images.githubusercontent.com/15173772/77514743-5e587e00-6e9d-11ea-877a-bd61575906d0.png)

-----

![Forum_–_Test_grp_–_beta_release_testing](https://user-images.githubusercontent.com/15173772/77514945-ba230700-6e9d-11ea-8e5b-aa34e9a607d3.png)

-----------

- [x] **2. Custom thumbnail add-on functionality is broken**

Please refer to this visual where I have shown how this admin-related setting does not work for custom thumbnail add-on w.r.t pre-release branch.

https://drive.google.com/file/d/1NGF5wcwnAaJ7b9p26lqyORYFKHAiYxvP/view

- [x] **3. Upload by Url add-on. When terms of services are enabled along with direct upload, it bypasses the validation and the file get uploaded without checking terms of services checkbox.**

https://drive.google.com/file/d/1W0N4mDPVFQHzGNqgAyf_AK35owS5sWgP/view

-------

- [x] **4. rtmedia Wordpress comment attachment** - Facing the same issue as mentioned in subtask 1

Please do the needful.

**Comment by SID177** [comment]
>4. rtmedia Wordpress comment attachment - Facing the same issue as mentioned in subtask 1

@kjnanda This seems to be working fine for me for `pre-release` of rtMedia core.
![Hello world! – localfw-rtmedia test](https://user-images.githubusercontent.com/23107546/77902693-3c953780-729f-11ea-86f0-60eebd85a0b5.gif)

**Comment by kjnanda** [comment]
@SID177 Please check my comment below.

Subtask - 1 ✅ 
Subtask 2 - Seems to be pending
Subtask 3 - Code needs to be merged into the branch
Subtask - 4 Works fine now. 

The reason is, you added the fix for subtask 1 and it was a similar issue hence you could not replicate it after the added fix.

**Comment by kjnanda** [comment]
@SID177 Added changes LGTM 👍

**Comment by kjnanda** [comment]
@SID177 Please check the below condition where upload operation is not working.

1. Upload terms of services enabled for both activity and media page - upload operation works at both places - ✅ 
1. Upload terms of services disabled for both activity and media page - upload operation works at both places - ✅ 
1. Upload terms of services disabled for activity and enabled media page - - upload operation works at both places - ✅ 
1. Upload terms of services enabled for activity and disabled media page - ❎ 

Please do the needful.

**Comment by kjnanda** [comment]
Adde changes LGTM @SID177

**Comment by kjnanda** [comment]
This has been fixed with rtMedia V4.6.1
