### ISSUE TITLE
Delete functionality issue

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1605]
Not able to perform delete operation with latest version of rtMedia plugin.

------

Please check below screencast - https://drive.google.com/file/d/1X4EVSz_dT2L1uIQcsbMFVnGEGBwy4QCn/view

-----

Delete functionality checklist

1. Delete the media using thumbnail hover event ✅ 
2. Delete the media from lightbox ❌ 
3. Delete the media from the single media page ❌ 

----

@SID177 Please fix this in High priority

**Comment by SID177** [comment]
This issue caused due to changes added in https://github.com/rtMediaWP/rtMedia/pull/1562 PR.

**Comment by kjnanda** [comment]
@SID177 I checked this functionality and this seems to be working fine

**Comment by kjnanda** [comment]
This is working as expected and tested with `dev` branch. ✅

**Comment by kjnanda** [comment]
Closing this issue as this has been fixed and release in - V4.6.2
