### ISSUE TITLE
[Uncaught Error:] Fix call to undefined function error thrown on media page when nouveau template is active and BuddyPress is inactive

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1608]
### Issue Description

When the Nouveau template is active then the media page shows many errors.

----

### Steps to reproduce an issue

1. Activate rtMedia and BuddyPress both
2. Enable Nouveau template
3. Goto /media page in the front end
4. Now, deactivate BuddyPress
5. Refresh the media page 
6. Observe that it throws many errors

----

### Attachment

![Media_–_test](https://user-images.githubusercontent.com/15173772/79445219-e98ae680-7ff9-11ea-9b73-1e1130f27fd8.png)

----

### Test Environment Used

```
WordPress - V5.4
BuddyPress - V5.1.2
rtMedia - V4.6.1
```
-----

PS: One of our customers also faced the same issue. `2572585` Please update him once the issue fixed and released.

**Comment by kjnanda** [comment]
@SID177 Please check my comment below.

1. When Legacy was active before BuddyPress gets deactivated then it shows proper the media available on the page

![Media_–_test](https://user-images.githubusercontent.com/15173772/79562184-3f2dc480-80c8-11ea-904d-27169176879d.png)

-----

2. When Nouveau was active before BuddyPress gets deactivated then it does not show the media available on the page

![Media_–_test](https://user-images.githubusercontent.com/15173772/79562400-a9df0000-80c8-11ea-9248-170877df9e35.png)

**Comment by SID177** [comment]
@kjnanda Are we supposed to handle showing `/media` page when BuddyPress is inactive?

**Comment by kjnanda** [comment]
@SID177 Can you please elaborate on your query?

**Comment by SID177** [comment]
@kjnanda I've showed the rtMedia template when Nouveau was last active, like it shows in case of Legacy template.

**Comment by kjnanda** [comment]
@SID177 This looks better now.

**Comment by kjnanda** [comment]
This is working as expected and tested with `dev` branch. ✅

**Comment by kjnanda** [comment]
Closing this issue as this has been fixed and release in - V4.6.2
