### ISSUE TITLE
Custom css code does not work as expected

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1609]
### Issue Description

With the latest rtMedia 4.6.1, the added custom CSS related changes are not working. Please do the needful. 

----

### Steps to reproduce an issue

1. Goto rtMedia Settings > Custom CSS tab
2. Add this code : `#buddypress form#whats-new-form textarea{border-color: red;}` into CSS textarea and click on Save Settings button
3. Goto Activity Page
4. As per the changes we added, the text area border should be displayed with `#ff0000` (Red) color
5. Observe that the changes does not work.

If you check the same thing with Version 4.6.0 then it will work. 

----

### Test Environment Used

```
WordPress - V5.4
BuddyPress - V5.1.2
rtMedia - V4.61
```

`2561273`

**Comment by SID177** [comment]
While fixing PHPCS issues, `rtmedia_custom_css` function was removed and https://github.com/rtMediaWP/rtMedia/commit/ab30d0914b900cc8bc4b96dc13d84b6e2bdd79bf#diff-f23e65e07ebeccfcd8de51efd0419621R1356-R1364 code was added as alternative.
But after this ☝️ commit, the new code was removed so custom css wasn't added. I've added the code again in https://github.com/rtMediaWP/rtMedia/pull/1617

**Comment by kjnanda** [comment]
@SID177 Please check and track such incidents with PHPCS fixes. I doubt there can be more hidden such things that we have to identify. You can check the PHPCS fixes PRs stored somewhere in the sheet.

**Comment by kjnanda** [comment]
@SID177 Added changes works as expected.

**Comment by kjnanda** [comment]
This is working as expected and tested with `dev` branch. ✅

**Comment by kjnanda** [comment]
Closing this issue as this has been fixed and release in - V4.6.2
