### ISSUE TITLE
Breaks the UI with latest changes in theme 2016 with Nouveau template

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1621]
Please check this visual- https://drive.google.com/file/d/1_yUbe-FCIQZmsN35u92MKHhxgZoAQXnG/view

**Comment by SID177** [comment]
@kjnanda This issue is fixed in https://github.com/rtMediaWP/rtMedia/pull/1620, which is now merged in `pre-release`

**Comment by kjnanda** [comment]
@SID177 Okay. 

Closing this issue as it was regression one.
