### ISSUE TITLE
Privacy Page redirection issue

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1624]
### Issue Description

Privacy settings show under the User's profile is no more accessible.

----

### Steps to reproduce an issue

Goto this link - http://<Site_Url>/members/<User_Name>/settings/privacy/

It should show a privacy option as shown in the below screenshot.

![Privacy_–_Settings_–_krupa_–_krupa_dev5_rt_gw](https://user-images.githubusercontent.com/15173772/79938656-d7d29480-847a-11ea-8d85-cc8c42b5fe8a.png)

----

### Attachment

![venting_site](https://user-images.githubusercontent.com/15173772/79938697-eb7dfb00-847a-11ea-80b5-2c1fab676c97.png)

----

### Test Environment Used

```
WordPress - V5.4
BuddyPress - V5.1.2
rtMedia - V4.6.1
```
----

`2574979`

**Comment by kjnanda** [comment]
@SID177 Looks good now! 

1. The privacy page is visible now
2. Changing the privacy works fine
3. Disabling the privacy removes `privacy` option from settings
4. Viewing the privacy setting in logged out mode is not a valid scenario

Let me know if there is anything else we need to check.

**Comment by SID177** [comment]
Changing privacy from logged out mode shouldn't be allowed and if such a thing happens then appropriate message should be displayed.
That's all I guess.

**Comment by kjnanda** [comment]
@SID177 I found one weird scenario

If you try to access this link `http://localhost/beta-testing/members/adminuser/settings/` then it will redirect the user to log in page which is fair enough.

But if you try to access this `http://localhost/beta-testing/members/adminuser/settings/privacy/` it will allow selecting the radio button. However, changes are not happening and it says `No changes were made to your account.` but this also should not be allowed. 

IMO, it should have the same behavior as other tabs inside `settings`

**Comment by SID177** [comment]
Yes, privacy page shouldn't be visible to users without login. But this behavior exists in older versions as well.
We can add a check in next version.

**Comment by kjnanda** [comment]
Yes, We are good to freeze this release now.

**Comment by kjnanda** [comment]
This is working as expected and tested with `dev` branch. ✅

**Comment by kjnanda** [comment]
Closing this issue as this has been fixed and release in - V4.6.2
