### ISSUE TITLE
Issue with Social sync add-on with rtMedi4.6.2 release

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1633]
Shows JavaScript lines of code on the site when `rtmedia social sync` add-on is active

-----

![screenshot-krupa dev5 rt gw-2020 04 27-11_45_04](https://user-images.githubusercontent.com/15173772/80339599-a7289b80-887c-11ea-897b-457382ae3ab4.png)

**Comment by SID177** [comment]
@kjnanda Do I have to insert app details to see this issue? Otherwise I'm not getting this

**Comment by kjnanda** [comment]
Yes, @SID177 

If you need you can use my site. You already have the credentials of my site. 

This is strange that the issue was not produced during the testing as I already conducted a test with all the add-ons! However, it appeared today. So let us fix this first. This has not been reported by customers yet!

**Comment by SID177** [comment]
Yes if we add app details the issue appears. Fixing it..

**Comment by kjnanda** [comment]
Closing this issue as this has been fixed and release in - V4.6.3
