### ISSUE TITLE
[Customer Query] Fix the fatal error issue with Yoast SEO plugin with rtMedia

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1635]
When Yoest SEO Plugin is active, it throws the below FATAL error.

> PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function RTMediaInteraction::rtmedia_wpseo_og_image(), 0 passed in /wordpress/core/5.4/wp-includes/class-wp-hook.php on line 287 and exactly 1 expected in /srv/htdocs/wp-content/plugins/buddypress-media/app/main/interactions/RTMediaInteraction.php:312"

------

`2575901` `2576004` `2576024`
`https://wordpress.org/support/topic/fatal-error-uncaught-argumentcounterror-too-few-arguments-to-function-rtmediai/#post-12752342`
Also, two more customers who checked us via email

**Comment by SID177** [comment]
`wpseo_opengraph` has been deprecated from Yoast SEO v14.0. We can use `wpseo_frontend_presenters` filter as an alternative.
The callback in this filter adds `<meta property='og:image'` under HTML `head`, which should be checked after fixing this.

**Comment by kjnanda** [comment]
@SID177 

> The callback in this filter adds <meta property='og:image' under HTML head on rtMedia's profile and group media (/media) page (When Yoast SEO is active), which should be checked after fixing this.

Do you mean to cross-check media page functionality after adding this fix?

Did I get it correct?

**Comment by SID177** [comment]
Check if these tags are there on media page
> <meta property="og:image" content=

![Screenshot 2020-04-30 at 1 53 20 PM](https://user-images.githubusercontent.com/23107546/80688825-0b03cc00-8aea-11ea-89f5-5dda03ee205f.png)

**Comment by kjnanda** [comment]
The added fix works as expected

**Comment by kjnanda** [comment]
Closing this issue as this has been fixed and release in - V4.6.3

Also, Nitun has updated the customer tickets of helpdesk, wp.org, and the customers who had connected us via email.
