### ISSUE TITLE
Time stamp is missing

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1636]
With the latest release t is found that the timestamp is missing. 

Please check the below screenshot. 

Expected Result: 

![krupa_–_foodmania](https://user-images.githubusercontent.com/15173772/80566014-8fcde780-8a0f-11ea-8653-2a9165820243.png)

-----

Actual Result: 

![Photo___admin___Media___Profile___rtMedia_Demo_Site](https://user-images.githubusercontent.com/15173772/80566228-213d5980-8a10-11ea-9ee1-cff7a8a6e7ae.png)

**Comment by SID177** [comment]
This issue is there since v4.6.1, it appeared due to PHPCS fixes. It was working in v4.6.0.

**Comment by kjnanda** [comment]
This is working as expected and tested with `pre-release` branch. ✅

**Comment by kjnanda** [comment]
Closing this issue as this has been fixed and release in - V4.6.3

Also, I have updated the customer ticket for the recent release.
