### ISSUE TITLE
Uploader Refactoring

### ISSUE THREAD

**Issue by rahul286** [rtMediaWP/rtMedia#28]
- [x] Cancel Uploading in Middle - Currently there is no way to cancel a upload in middle. Useful if user selects wrong or large file accidentally for upload.
- [ ] The current uploader doesn't throw many errors. The redirection after upload is incorrectly hooked. Even if upload fails, the redirection still happens. (from #125)
- [x]  I would be great if the upload form could be used on other places of the site. (from #226 )

**Comment by kjnanda** [comment]
Not able to replicate the subtask 2. It seems to be fixed. Closing this issue.
