### ISSUE TITLE
Users do not have the possibility to delete comments other users added to their uploaded pictures

### ISSUE THREAD

**Issue by ifs-net** [rtMediaWP/rtMedia#422]
Actually a user can upload several pictures. These pictures can be commented by other users individually or inside the activity-stream.
In huge communities the use case might appear that some users post comments for other users pictures that are disliked by the photo uploading users. It would be great to have the possibility that users can delete comments other users made for their photos.
Maybe you can include this into one of your next releases?

PS: Thanks a lot for your great plugin!

**Comment by kjnanda** [comment]
I believe this has been already added so closing this ticket.
