### ISSUE TITLE
Better styling for albums

### ISSUE THREAD

**Issue by rahul286** [rtMediaWP/rtMedia#506]
There must be visual difference between styling for a single media and album.
Something like "folder" effect, or "border" can be added to album.

**Comment by kjnanda** [comment]
@dishitpala Please look into this. I checked the code and it seems to be ready. 

Please do the needful to finish it properly.

**Comment by pooja-muchandikar** [comment]
I have cross-checked this issue on `pre-release` branch and looks fine. An border is been added to the albums.

**Comment by pooja-muchandikar** [comment]
Released with 4.5.11 version
