### ISSUE TITLE
Silverlight - Loading animation / Javascript Error

### ISSUE THREAD

**Issue by maximus-meridius** [rtMediaWP/rtMedia#507]
Hello, 

we have an issue that has been there for about a year. 

We have tested your online demo on http://demo.rtcamp.com/rtmedia/ and this is the same screenshot I get on another site we looked after. 

![untitled](https://f.cloud.github.com/assets/5479186/1869093/608ea34e-7876-11e3-8f6d-00543f677dc8.png)

This is the same error we get on our site: 

http://screencast.com/t/abefiXpH4R

I also get this error message in the IE debugging tool 

---

throw new Error("Unhandled Error in Silverlight 2 Application: [Format_BadBoolean]\nArguments: \nDebugging resource strings are unavailable. Often the key and arguments provide sufficient information to diagnose the problem. See http://go.microsoft.com/fwlink/?linkid=106663&Version=5.1.20913.00&File=mscorlib.dll&Key=Format_BadBoolean\n   at System.Boolean.Parse(String value)\n   at System.Convert.ToBoolean(String value)\n   at Moxiecode.Plupload.Page..ctor(IDictionary`2 init_params)\n   at Moxiecode.Plupload.App.OnStartup(Object sender, StartupEventArgs e)\n   at MS.Internal.CoreInvokeHandler.InvokeEventHandler(UInt32 typeIndex, Delegate handlerDelegate, Object sender, Object args)\n   at MS.Internal.JoltHelper.FireEvent(IntPtr unmanagedObj, IntPtr unmanagedObjArgs, Int32 argsTypeIndex, Int32 actualArgsTypeIndex, String eventName, UInt32 flags)");

SCRIPT5022: Unhandled Error in Silverlight 2 Application: [Format_BadBoolean]
Arguments: 
Debugging resource strings are unavailable. Often the key and arguments provide sufficient information to diagnose the problem. See http://go.microsoft.com/fwlink/?linkid=106663&Version=5.1.20913.00&File=mscorlib.dll&Key=Format_BadBoolean
   at System.Boolean.Parse(String value)
   at System.Convert.ToBoolean(String value)
   at Moxiecode.Plupload.Page..ctor(IDictionary`2 init_params)
   at Moxiecode.Plupload.App.OnStartup(Object sender, StartupEventArgs e)
   at MS.Internal.CoreInvokeHandler.InvokeEventHandler(UInt32 typeIndex, Delegate handlerDelegate, Object sender, Object args)
   at MS.Internal.JoltHelper.FireEvent(IntPtr unmanagedObj, IntPtr unmanagedObjArgs, Int32 argsTypeIndex, Int32 actualArgsTypeIndex, String eventName, UInt32 flags) 
eval code (2), line 1 character 1

---

Can anyone help asap as this problem with IE has been causing us a lot of issues.

Would it be possible to disable the use of silverlight completely from anywhere in the code? 

Thanks

**Comment by kjnanda** [comment]
> Sorry to say that but we cannot provide any more support on the issue as we tested plugin on IE.

Considering the above comment, I am closing this issue.
