### ISSUE TITLE
Import/export option for admin settings

### ISSUE THREAD

**Issue by Ritesh-patel** [rtMediaWP/rtMedia#554]
Some users initially setup rtMedia on their development site and later use it on the production site and they have to go through same admin settings process on production site to setup rtMedia. It will be nice if we add import/export option for admin settings.

**Comment by thrijith** [comment]
Feature added in rtMedia version 4.5.0

PR Ref: [#1091](https://github.com/rtMediaWP/rtMedia/pull/1091)
