### ISSUE TITLE
Add dynamic activity actions for translation of activity items

### ISSUE THREAD

**Issue by BoweFrankema** [rtMediaWP/rtMedia#580]
Hi guys,

I would like to request that the activity strings generated by RTMedia would be created dynamically. This is possible since BuddyPress 2.0 and has the benefit that the new entries are translatable (which is crucial for multilingual BP communities). 

This is important because currently if a user posts an RtMedia item,  the activity item text would be recorded in their native language and thus displayed to other users in that language as well. By making the activity actions dynamic the activity entry would be displayed in the language of the user itself :-)

Please see the following ticket to for instructions: https://buddypress.trac.wordpress.org/changeset/8125

Thanks in advance guys :-)

**Comment by nitun** [comment]
This issue has been fixed earlier. Closing this now.
