### ISSUE TITLE
Image Navigation

### ISSUE THREAD

**Issue by schwarzaufweiss** [rtmediawp/rtMedia#584]
A friend of mine was asking if there is no way to navigate through images – why it would be needed to click "back" onto the images tab and then with a second click on the next image... Yes, it would be nice to have some kind of next/back arrows – or any kind of click-through navigation. If there are a lot of images in a BP profile or in a group, the way it is at the moment is really time consuming.

**Comment by nitun** [comment]
Added lightbox with next/previous arrow.
