### ISSUE TITLE
JS Error: "TypeError: el is undefined" (rtmedia.js line 682)

### ISSUE THREAD

**Issue by mewcrazy** [rtmediawp/rtMedia#632]
Hello,
My browser are showing me an error in my debug console:

"TypeError: el is undefined" in rtmedia.js line 682

**Comment by Ritesh-patel** [comment]
Hi @mewcrazy 

Did it throw same error when you check it with WordPress default theme and other plugins disabled? Just want to make sure that whether it's theme related issue or a plugin conflict.

**Comment by nitun** [comment]
I hope this issue has been resolved with latest rtMedia version. If you face any other issues, please let us know.
