### ISSUE TITLE
Video (Media) Upload - Buddypress

### ISSUE THREAD

**Issue by meeekz** [rtmediawp/rtMedia#644]
It would be great if you could enhance rtMedia as follows:

For media albums and and video's, provide a cover photo option for display.
For video upload, provide a progress bar so we can tell when the upload is complete?

Regards,
mika

**Comment by nitun** [comment]
@meeekz 

rtMedia Video custom thumbnail add-on will be helpful to use cover photo for the video file. 

Progress bar for any media file uploads already added in rtMedia core plugin.
