### ISSUE TITLE
Single post links don't work

### ISSUE THREAD

**Issue by cadaar** [rtmediawp/rtMedia#657]
All the links in a post page are opened in the Magnific Popup lightbox, included user profile, Edit and Reply links.

**Comment by jigneshnakrani088** [comment]
@cadaar 

This may be theme css issue, did you tried this with WordPress default theme? Or which theme you are using.?

For any further queries or issue you can create support ticket on [our community](http://community.rtcamp.com/) form.

**Comment by cadaar** [comment]
Hi @jigneshnakrani088,

I am using Kleo theme, do you have some idea of what I could do to at least temporary fix it? 
Thanks in advance.

**Comment by nitun** [comment]
@cadaar rtMedia and Kleo theme are well compatible with each other. 

If you are still facing any issues, please create a support topic on [community forum](http://community.rtcamp.com/c/rtmedia).
