### ISSUE TITLE
the icon is not aligned to "delete album" text

### ISSUE THREAD

**Issue by dt2505** [rtmediawp/rtMedia#661]
the icon for menu item "delete album" is not aligned to its text associated, shown as below

![screenshot from 2015-08-23 21 58 39](https://cloud.githubusercontent.com/assets/11011249/9428125/64995224-49e2-11e5-95e2-a1d041c6189d.png)

**Comment by Ritesh-patel** [comment]
Hello @dt2505 

It looks like a CSS issue. Please check it once with WordPress default theme and other plugins disabled, it might be theme issue or a plugin conflict.

**Comment by nitun** [comment]
No reply on this issue from a long time. Closing this now. If have any other issue, please create a new issue.
