### ISSUE TITLE
Not using BuddyPress causes fatal error

### ISSUE THREAD

**Issue by gabrielmerovingi** [rtmediawp/rtMedia#676]
When saving an image that is edited in the author archive, a fatal error is thrown as bp_is_active() is not available.

Error originates from:
app/main/controllers/template/RTMediaTemplate.php line 277.

Adding in a function_exists check resolves this.

**Comment by pranali333** [comment]
We have released reMedia v3.9.3 with the issue fixed. Please update the same.

Thanks.

**Comment by nitun** [comment]
This issue already fixed. Closing this issue now.
