### ISSUE TITLE
RT Media Plugin On Buddy Press

### ISSUE THREAD

**Issue by drivensnow** [rtmediawp/rtMedia#679]
Hey,

Bit weird this site but if it gets my problem sorted am down with the whole branch master thingy. 

I have a rtmedia installed on the buddypress platform. Before I upload and image the page is scuwiff and unaligned around the buttons at the top blah blah blah see pic, I've added some screen shots and chatted about it on there, saves me branching of on here.. thanks in advance for your time

:

**Comment by drivensnow** [comment]
[rtmedia error.pdf](https://github.com/rtCamp/rtMedia/files/72354/rtmedia.error.pdf)
 yeah sort of forgot to add it to initial post lol thanks

**Comment by nitun** [comment]
@drivensnow those mentioned issues still on your website? Lately, we fixed number of UI related issues with rtMedia. Please update the plugin and let us know.
