### ISSUE TITLE
No Scrolling

### ISSUE THREAD

**Issue by KeksKartoffe** [rtmediawp/rtMedia#680]
I can't scroll on the media page, i'm using "corolib - sparkling" theme.

http://blockylife.de/mitglieder/pinki2101/media/

**Comment by nitun** [comment]
@KeksKartoffe refer this http://community.rtcamp.com/t/cannot-scroll-the-page/5410. Hope it will help you.

**Comment by nitun** [comment]
I hope provided link solved this issue. Closing it.
