### ISSUE TITLE
Flickering icon

### ISSUE THREAD

**Issue by shkesar** [rtmediawp/rtMedia#688]
![rama mishra farmercity](https://cloud.githubusercontent.com/assets/5822067/14762526/33d96b92-099a-11e6-9bfb-9f20078438c6.png)
![rama mishra farmercity1](https://cloud.githubusercontent.com/assets/5822067/14762527/365f3126-099a-11e6-9825-a445d87c9bc3.png)

This happens when the website loads on both Chrome and Safari. I want to help resolve this so either help or guidance is encouraged.

**Comment by nitun** [comment]
Sorry for the delay in reply on this issue @shkesar . In this issue, you are talking about the `FC` logo on top? I don't think it's related to rtMedia plugin. But if this issue still persist, please provide me more details.

**Comment by nitun** [comment]
No reply yet. Closing this issue now.
