### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by kennynaoh** [rtmediawp/rtMedia#718]
Hello @Ritesh-patel ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there is a question want to ask.
I want to confirm with you about the main file need to be grab on [github](https://github.com/rtCamp/rtMedia).
`app/assets/js/rtMedia.backbone.js`
`app/assets/js/rtMedia.js`
`app/assets/js/rtmedia.min.js`
`app/assets/css/rtmedia.css`
`app/assets/css/rtmedia.min.css`
Am I right?
Please help me confirm that.
And if any other files need to be grab, please tell me.
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/6713

**Comment by chandra-patel** [comment]
Hello @kennynaoh 

Yes, all file you mentioned.

Please also add this `app/assets/js/vendors/magnific-popup.js`

**Comment by kennynaoh** [comment]
Thanks @chandra-patel
