### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by HanifaScraps** [rtmediawp/rtMedia#734]
Hi there,
I'v step up rmedia just like the demos, and creat a page where I put this short code:
[rtmedia_gallery global="true" media_type="photo" media_author="1"]
But when I go the the page it's say's: !" There's no media found for the request !"
But I add a lot of photos in my profile with the rmedia... 
Can you help me with this to see where is the bug?
Kind Regards

**Comment by nitun** [comment]
This issue has been discussed on community forum http://community.rtcamp.com/t/galery-page-not-working/7372/4 and it resolved. Closing this issue now.
