### ISSUE TITLE
Feature Request - Allow image Tagging to include the names of Attributes, instead of only other members/users

### ISSUE THREAD

**Issue by darrenfulton** [rtMediaWP/rtMedia#744]
Instead of being able to tag things in images with a user/member, I think it would be great to be able to tag photos with items that are stored using the "Custom Attributes" feature. For example, If I have a Custom Attribute defined that is "Steamboat" and another that is "Speedboat", I should be able to Tag an image and identify the steamboat in the picture or the speedboat in the picture.

**Comment by nitun** [comment]
Tagging a friend to Photo is a different thing than tag any custom attribute to that photo. People will get confused while tagging whether to tag friends or attributes when they start searching name.
Another way, it will be more clutter if every user supposes to tag attribute on the same photo. 

So it's better to only photo author can edit his/her own uploaded photo and change the custom attribute.

**Comment by darrenfulton** [comment]
I'm sure that I have a good use case for this feature, so I'd appreciate if you'd do it.  I'm sure some other folks would be able to use it as well.  Make it optional and disabled by default, but I'd like my users to be able to tag items within an image with a predefined rtmedia attribute that has been added by the administrator, in addition to tagging members.  Thanks!

**Comment by kjnanda** [comment]
Hi @darrenfulton,

Sorry for the delay in reply. 

I read your requirement but Nitun already explained to you the scenario and also an alternate solution for this. This could be the imp feature for you but this is not in our to-do list. I hope you understand our concern.

I am closing this ticket.

Thanks,
Krupa
