### ISSUE TITLE
Audio Player reverting to 'Download' window 

### ISSUE THREAD

**Issue by JenkNZ** [rtMediaWP/rtMedia#756]
http://digitaldiggers.co.nz/groups/producers/
Audio uploads result in audio player changing into 3 different states. 

1 second:
![44a146fb35661b644135281424b8a392d186c896](https://cloud.githubusercontent.com/assets/23047803/19676636/f6129600-9af1-11e6-9b5f-df5f6d186913.png)

3 seconds:
![2c4e485170c98d166f802b2d0fb91aa1633d5839](https://cloud.githubusercontent.com/assets/23047803/19676657/0d5a8bec-9af2-11e6-9cf7-0347f8853bb0.png)

10 seconds:
![a15d465744d1ac4e4dbdc213fa007cc08241dbee](https://cloud.githubusercontent.com/assets/23047803/19676663/13fa7dea-9af2-11e6-9739-efedac703a3e.png)`
Home URL    http://digitaldiggers.co.nz
Site URL    http://digitaldiggers.co.nz
PHP 5.4.45
MYSQL   5.5.51
WordPress   4.6.1
BuddyPress  2.7.0
rtMedia 4.1.8
OS  Linux
Imagick ImageMagick 6.7.6-8 2016-07-19 Q16 'www.imagemagick.org'
GD  bundled (2.1.0 compatible)
[php.ini] post_max_size 64M
[php.ini] upload_max_filesize   64M
[php.ini] memory_limit  256M

**Comment by nitun** [comment]
Not able to reproduce this issue. If you are using other than mp3 format of audio file, please use transcoder plugin https://wordpress.org/plugins/transcoder/ along with rtMedia plugin.
