### ISSUE TITLE
Masonry on Activity stream

### ISSUE THREAD

**Issue by creativenoobie** [rtMediaWP/rtMedia#787]
Hey,

I would like to propose Masonry on Buddypress Activity stream.
As we know that, rtMedia uses a simple way of displaying the pictures on front-end, How about we replace it by Masonry?
rtMedia Inspirebook (A facebook styled theme) is missing this feature too, making it incomplete to look like facebook.

Here's an attractive example: [Screenshot Masonry](http://demo.latestmasala.com/wp-content/uploads/2016/11/Captureco2mment.png)

rtMedia is really flexible with cool plugins and addons but this is something basic that rtMedia should offer.

**Comment by joelabreo** [comment]
Hi @creativenoobie ,

Thank you for your feedback.

We are already working on adding this feature to a future version of rtMedia. Stay tuned! ;)

Joel Abreo

**Comment by creativenoobie** [comment]
Hey @Joelabreo,

Thanks for the follow-up..
I seriously can't wait for the update. I'm very much excited for the same. I'm sure there will be many members like me.

Thanks to rtCamp team for working hard. In the meantime, I'll wait.

**Comment by creativenoobie** [comment]
Hey @Joelabreo,

Today, I  updated rtmedia to 4.2.1. 
But couldn't see the Masonry in this version. I know you guys are working hard to introduce new features and fix the security issues. 
That being said, I would like to know the status of the development. (Too excited for this!)

Thanks!

**Comment by joelabreo** [comment]
Hi @creativenoobie ,

rtMedia v4.2.1 was a point release, mainly focused on security fixes. 

Adding Masonry to the Activity feed is at the top of our list of new features, with one of our developers already working on it. I cannot give you an ETA, though :( 

Regards,

Joel Abreo

**Comment by creativenoobie** [comment]
Hey @Joelabreo,

Any update?

**Comment by nitun** [comment]
@creativenoobie it's still in development. It may take some time. Progress can be found here https://github.com/rtMediaWP/rtMedia/pull/807

**Comment by raftaar1191** [comment]
@pranali333 

After merging the following PR https://github.com/rtMediaWP/rtMedia/pull/807 and releasing 

Please update the document for the filter `rtmedia_masonry_in_activity_enable` 
Documentation for the filter is the below gist link: 
https://gist.github.com/raftaar1191/f42f6007d37e91e4c8edf74deed05960

**Comment by creativenoobie** [comment]
Hey,

I'm really excited for the update after all the updates so far. I know it might sound annoying, but may I know if I can expect this feature in upcoming update? And also, When are you going to release next update?

Thanks a ton for making it work.. I appreciate your hard work.

**Comment by creativenoobie** [comment]
@nitun, @raftaar1191 

Any updates? A member created similar request:
https://github.com/rtMediaWP/rtMedia/issues/876

We all are getting excited and I'm waiting since Nov 2016. ETA will be appreciated.

**Comment by BhargavBhandari90** [comment]
This has been done in https://github.com/rtMediaWP/rtMedia/issues/876. So closing this.

**Comment by pranali333** [comment]
Hi @creativenoobie ,

With rtMedia version 4.4, we have brought masonry to the Activity feed. Please, once update the same on your website and let us know if that works fine for you or you face any issue.

Regards,
Pranali

**Comment by creativenoobie** [comment]
Thank you so much Team RTCamp. It was a great experience, Will let you know if I experience any issues.
