### ISSUE TITLE
In README.md file all links with "=" pointing at incorrect URLs

### ISSUE THREAD

**Issue by gagan0123** [rtMediaWP/rtMedia#824]
![screen shot 2017-02-27 at 3 25 46 pm](https://cloud.githubusercontent.com/assets/1535505/23356755/1129d36a-fd01-11e6-9d29-4110adbe0ba5.png)

**Comment by mangesh** [comment]
Hi, @gagan0123 Thank you for pointing this out. It was happening due to the faulty deploy ( readme.txt to README.md converter ) script.
We have fixed it.
