### ISSUE TITLE
Add filter to allows users to change text "Media Gallery" under shortcode gallery

### ISSUE THREAD

**Issue by pranali333** [rtMediaWP/rtMedia#825]
We have a filter to change text "Media Gallery" under the user profile tabs but we are missing a filter which allows users to change this text under shortcode gallery.

Please, add one for the same.

Reference file: `media-gallery.php`
Reference document for existing filter for Media tab: https://rtmedia.io/docs/developers/hooks/filter-to-change-media-gallery-header-title/

Thanks,
Pranali

**Comment by thrijith** [comment]
@pranali333 using `rtmedia_gallery_title` will update title for media tab gallery and for shortcode gallery also. Please refer [this](https://drive.google.com/drive/folders/1u0XPbfZQlhTLM46qcV2rRG2wBLk7fRnM), and let me know if we need a new filter or not.

**Comment by kjnanda** [comment]
this same filter is working fine for shortcode so no need to introduce anything separately for shortcode.
