### ISSUE TITLE
Allow to replace the text "Like/dislike" with any icon.

### ISSUE THREAD

**Issue by pranali333** [rtMediaWP/rtMedia#826]
Right now we only have a filter to change the text with some other text. To change the text with a new icon like heart and change the color when someone dislikes will include some JavaScript file related changes. 

Thus, we will need to first add support for such custom code in our plugin.

**Comment by BhargavBhandari90** [comment]
This has been done.
Here is the documentation.

Output:

![like-icon](https://cloud.githubusercontent.com/assets/19459637/25775285/7f15d290-32bf-11e7-9360-6c7ef73cbec2.png)

**Comment by BhargavBhandari90** [comment]
New PR is: https://github.com/rtMediaWP/rtMedia/pull/865

**Comment by pranali333** [comment]
Fixed and released.
