### ISSUE TITLE
Show media count in rtMedia gallery shortcode

### ISSUE THREAD

**Issue by raftaar1191** [rtMediaWP/rtMedia#828]
Show media count in rtMedia gallery shortcode

Need to add a parameter in gallery shortcode to show the media count in gallery

Example: `[rtmedia_gallery global="true" show_count="true"] `

**Comment by raftaar1191** [comment]
@pranali333
Here is the PR link #829 for the above issue

**Comment by pranali333** [comment]
Duplicate issue 

https://github.com/rtMediaWP/rtMedia/issues/830

**Comment by pranali333** [comment]
Please, improve the default styling.

![show-count-shortcode](https://cloud.githubusercontent.com/assets/7771963/25742366/c65011ac-31ac-11e7-82b9-a7f3d1b53f99.png)

Thanks.

**Comment by BhargavBhandari90** [comment]
This has been fixed. Here is the PR: https://github.com/rtMediaWP/rtMedia/pull/857

**Comment by rahul3883** [comment]
Our team has decided to remove this feature from rtMedia core.
If you want to add this feature to your site, refer to the below link.
https://rtmedia.io/docs/developers/add-media-count-media-gallery/
