### ISSUE TITLE
Media count for Gallery shortcode

### ISSUE THREAD

**Issue by joelabreo** [rtMediaWP/rtMedia#830]
The Gallery shortcode doesn't currently have any way of displaying a count of how many media it is displaying. 

I propose the addition of a "media_count" type parameter to the Gallery shortcode. If passed, the media Gallery will display a count of the total number of media items that have been fetched.

**Comment by pranali333** [comment]
Related PR details https://github.com/rtMediaWP/rtMedia/issues/828
