### ISSUE TITLE
rtmedia_comments_enabled() Function may generate notice.

### ISSUE THREAD

**Issue by yahilmadakiya** [rtMediaWP/rtMedia#838]
The **rtmedia_comments_enabled()** function may generate notice/fatal. This should be like **get_rtmedia_default_privacy()** function. 

Ref: https://github.com/rtMediaWP/rtMedia/blob/develop/app/main/controllers/template/rtmedia-functions.php#L2542

**Comment by thrijith** [comment]
Fixed in rtMedia version 4.5.1

PR Ref: [#1139](https://github.com/rtMediaWP/rtMedia/pull/1139)
