### ISSUE TITLE
Shows PHP Notice for list view on upload.php page

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#843]
![list view](https://cloud.githubusercontent.com/assets/15173772/24244752/32982f40-0fe6-11e7-8c6a-0aa44702b1f8.png)

**Comment by dharmin** [comment]
Merged PR #1358 for this issue.

**Comment by kjnanda** [comment]
Tested with dev branch and I don't see any Notices now.

**Comment by kjnanda** [comment]
Test with master branch and I don't see any such Notices now
