### ISSUE TITLE
Comment in media option not Working for Mobile deveice

### ISSUE THREAD

**Issue by raftaar1191** [rtMediaWP/rtMedia#846]
In mobile, Comment in media option is not working. 
When user open the media in popup and the media type is video or audio the uploder button in comment is not working.
![screenshot_2017-03-31-12-34-03](https://cloud.githubusercontent.com/assets/22215595/24539922/6d735d28-160e-11e7-91ba-8fba25111007.png)

**Comment by oliziplok** [comment]
Do you have any updates on this?
