### ISSUE TITLE
JavaScript error while deleting media

### ISSUE THREAD

**Issue by pranali333** [rtMediaWP/rtMedia#847]
This issue occurs only when rtMedia is activated and BuddyPress is not present.

Try deleting media from media gallery ( generated from shortcode ).

You should get below browser error.

![delete-media-issue](https://cloud.githubusercontent.com/assets/7771963/24544470/0ab4be76-1621-11e7-913a-80603a33ff56.png)

Please, look into this.
I hope it will be fixed soon.

Thanks.

**Comment by raftaar1191** [comment]
@pranali333 
Here is the PR link #829 for the above issue
