### ISSUE TITLE
Improvise comment media setting

### ISSUE THREAD

**Issue by pranali333** [rtMediaWP/rtMedia#848]
The below setting seems misleading. Please, make it more clear.

![comment-media-doubt](https://cloud.githubusercontent.com/assets/7771963/24741395/52a26098-1ac3-11e7-8a2d-78f117daa82f.png)

The second setting to disable media upload in already commented media should not display with the default feature.

Thanks.

**Comment by raftaar1191** [comment]
@pranali333 
Here is the PR link https://github.com/rtMediaWP/rtMedia/pull/829 for the above issue

**Comment by raftaar1191** [comment]
Here is the hook link that will allow user to add media inside the another media ( Comment media )

`https://rtmedia.io/docs/developers/hooks/rtmedia_disable_media_in_commented_media/`
