### ISSUE TITLE
Check edit media functionality when BuddyPress Activity Streams setting is disabled 

### ISSUE THREAD

**Issue by pranali333** [rtMediaWP/rtMedia#859]
Whenever the user edits the media, gets `HTTP ERROR 500`.

Turning the BuddyPress Activity Streams setting ON solves the issue.

Please, look into the issue and debug the cause.

Thanks,

**Comment by BhargavBhandari90** [comment]
This has been tested and working fine now.

**Comment by rahul3883** [comment]
Fixed [here](https://github.com/BhargavBhandari90/rtMedia/commit/9dcf92f135a8a00cfd5813e9e7e8defaf981572c)
