### ISSUE TITLE
Please provide the text area to add Album description along with album name while creating the new album.

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#875]
As we are providing an option to Show album description in rtMedia Settings, It will be more helpful to users if we provide a text area to add `Album Description` as well.  To use this feature in real time, the user has to purposely go through some extra steps as stated below.

1. After creating the album, the user has to go to that album single page and has to click on edit album link.
2. Add Description to the album.
3. Click on submit button.
4. Again go to album page and click on the album we have created.
5. Finally, the user will see what he wants!

So to avoid all the process simply we can add text area as suggested above.

**Comment by kjnanda** [comment]
@Sidsector9 I Cross checked this at my end. Functionally it works as expected. 
Please check the below points for UX perspective. 

1. Autofocus should work when the user clicks on `Add Album link`.
2. After creating the first album and continuing it, tab key focuses on `Album desc` text area but I don't see mouse pointer over there.

**Comment by Sidsector9** [comment]
@kjnanda we've tried resolving point 1 but no luck yet, point 2 is resolved. Adding a new album will set the cursor to the title again.
