### ISSUE TITLE
Activity media collage

### ISSUE THREAD

**Issue by rahul3883** [rtMediaWP/rtMedia#876]
We can show media collage on BuddyPress activity stream.

It should look like the below image:
![media collage](https://cloud.githubusercontent.com/assets/16514090/25986774/e792f5f2-370e-11e7-8a28-5c74c1803405.png)

**Comment by BhargavBhandari90** [comment]
Now it will be like

**Comment by BhargavBhandari90** [comment]
Provided option to
![option](https://cloud.githubusercontent.com/assets/19459637/26302306/6a540856-3f01-11e7-9565-5b25154ec838.png)
 enable/disable it.

**Comment by kjnanda** [comment]
@BhargavBhandari90 Things works fine for masonry.
But the media will look proper only if the page is reloaded explicitly when uploaded media is more than `3`. Please check the screen shots.

![1](https://cloud.githubusercontent.com/assets/15173772/26311895/6d2fb6b6-3f23-11e7-87b2-b1abaedc8eea.png)
![2](https://cloud.githubusercontent.com/assets/15173772/26311907/745b7506-3f23-11e7-9abe-a3371e6436ef.png)

Can we arrange them properly by default?

**Comment by kjnanda** [comment]
@BhargavBhandari90 Please correct the typo here. 

![unnamed image](https://cloud.githubusercontent.com/assets/15173772/26312121/3fc2bc90-3f24-11e7-987b-498d79c68186.png)

**Comment by kjnanda** [comment]
@BhargavBhandari90 The horizontal and verticle gap seems uneven.

![3](https://cloud.githubusercontent.com/assets/15173772/26312299/c35fd10a-3f24-11e7-9e19-419a6a438636.png)

**Comment by BhargavBhandari90** [comment]
@kjnanda All things reported by you is done now. You can cross check now.

**Comment by kjnanda** [comment]
@BhargavBhandari90 Cross checked fixed issues. Looks good now. 👍

**Comment by pranali333** [comment]
@BhargavBhandari90 

Please, first check if BuddyPress plugin is active or not to show the admin setting for Masonry view.

![buddypress-active-check](https://cloud.githubusercontent.com/assets/7771963/26349500/94ac4a24-3fcd-11e7-96b9-9b8fb1912d9b.png)

Thanks.

**Comment by BhargavBhandari90** [comment]
@pranali333 this has been done.
