### ISSUE TITLE
Using window.onload :(

### ISSUE THREAD

**Issue by demon-ru** [rtMediaWP/rtMedia#882]
After some updates I have a bug: upload container does not visible after click.
The reason is using window.onload in app/assets/js/rtMedia.js
And other (theme) using it in js code.

I think this code should be replaced by something more secure.

**Comment by pranali333** [comment]
Hello,

Can you please explain your issue in more detail?
Kindly, provide some screenshots and the debug info log on your website. You can find it under rtMedia Settings -> Supports tab. We will regenerate the issue on our end to make necessary improvements.

Thanks.

**Comment by demon-ru** [comment]
more detail.

there are:
1. one plugin with JS using "window.onload = function1;"
2. one theme (or other plugin) with JS using "window.onload = function2;"

Case:
What is the value of window.onload after simultaneous loaded these two JS?
Yes. It depends on what script last set value. 
The first set will not get executed handler.

Some plugins use the way: save the old value before setting handler and call it into function.
The best way: to find another way. Why the presence of jQuery( document ).ready() is additionally used window.onload?

I hope I could explain using clumsy English :)

**Comment by demon-ru** [comment]
The same my issue for theme: https://aquoid.com/forum/viewtopic.php?f=2&t=32896

**Comment by pranali333** [comment]
Hello,

Thanks for the explanation. Yes, we got your issue correctly and we will look into it.

I will update you soon regarding this.

Thanks for reporting this to us.

**Comment by BhargavBhandari90** [comment]
@demon-ru Can you confirm with the PR:https://github.com/rtMediaWP/rtMedia/pull/899

**Comment by demon-ru** [comment]
After plugin update:
1. upload container visible after click. Bug fixed
2. window.onload is still using in app/assets/js/rtMedia.js without save prior value.
I guess it will be troubles in future. At least with theme suffusion.

**Comment by BhargavBhandari90** [comment]
@demon-ru We checked with all default themes and there is not any issue with it.
