### ISSUE TITLE
If 2017 theme is activated some of the option available as pop up after click event under single album page is not completely visible

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#883]
Please check this link - https://drive.google.com/file/d/0B22UX8wWXPPReFFIazRGTmZobkU/view

**Comment by BhargavBhandari90** [comment]
This can't be fixed in rtMedia. So created a document for it.
Here is the document: https://github.com/rtMediaWP/library/blob/develop/media/rtmc_media_options_overflow_fix.txt
