### ISSUE TITLE
Auto scroll issue while uploading and/or adding comment on uploaded media. 

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#884]
The issue appears on Lightbox and Single media page both.

https://drive.google.com/file/d/0B22UX8wWXPPRdWRxcTNSQXJqcE0/view

**Comment by malavvasita** [comment]
This issue seems to be resolved and released in rtmedia v4.4.8

Mentioned this issue in Issue link: #1070 
PR for this issue: [#1073](https://github.com/rtMediaWP/rtMedia/pull/1073)

@kjnanda Can you please verify if this issue is present in current version of rtMedia?

**Comment by kjnanda** [comment]
@malavvasita I cross checked this at my end. This has been fixed.

**Comment by malavvasita** [comment]
Closing this issue as it is already fixed in rtMedia v4.4.8 :+1:
