### ISSUE TITLE
Lightbox - image width seems bit smaller. shows white strip in LHS

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#885]
Please check this video.
https://drive.google.com/file/d/0B22UX8wWXPPReWNSd09kc0xFelE/view

This issue is specific to `Theme 2015`

**Comment by Sidsector9** [comment]
@kjnanda This is fixed, kindly test it.

**Comment by kjnanda** [comment]
@Sidsector9 Looks good to me.

**Comment by kjnanda** [comment]
@Sidsector9 This looks good now. It doesn't show white strip in now. 👍

**Comment by BhargavBhandari90** [comment]
This is released.
