### ISSUE TITLE
Comment and like privacy issue

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#886]
If I add any post under private privacy option then activity created for comment and like should be private for the same. 

As per current scenario - Parent activity is private but generated child activity is not private. Please check video.

https://drive.google.com/file/d/0B22UX8wWXPPRVDAxWWZVc1ZjX1k/view

**Comment by Sidsector9** [comment]
@BhargavBhandari90 @kjnanda This issue has been fixed, kindly test.

**Comment by sumeetsarna** [comment]
Tested with this PR https://github.com/rtMediaWP/rtMedia/pull/912 . This issue is confirmed to be fixed.
