### ISSUE TITLE
Provide a filter to change the "alt" attribute value

### ISSUE THREAD

**Issue by pranali333** [rtMediaWP/rtMedia#936]
Currently, rtMedia sets the file name as the value for media's alternative attribute.
We can provide a filter which can allow the user to set this value as per their requirement.

![alt-attribute-filter](https://user-images.githubusercontent.com/7771963/28014620-ef49a9a8-658a-11e7-8249-548d4c38ac76.png)

Thanks.

**Comment by Sidsector9** [comment]
This is added here #946

**Comment by pranali333** [comment]
Released with version 4.4.3
