### ISSUE TITLE
Compatibility issue with latest WP Smush

### ISSUE THREAD

**Issue by BhargavBhandari90** [rtMediaWP/rtMedia#954]
Uploaded image is not showing in the media library.

**Comment by kjnanda** [comment]
Checked with the latest (Version 3.3.2) and not able to replicate the issue mentioned. Images are there in the media library.

![Media_Library_‹_krupa-rtmedia-plugins_dev2_rt_gw_—_WordPress](https://user-images.githubusercontent.com/15173772/69614070-8e5f5400-1058-11ea-81f1-590fdeb2e262.png)
