### ISSUE TITLE
Not able upload multiple images on IOS

### ISSUE THREAD

**Issue by BhargavBhandari90** [rtMediaWP/rtMedia#967]
We can not upload multiple images from IOS

**Comment by BhargavBhandari90** [comment]
It was intentional that not allow selecting multiple files into mobile devices.
But for those who want to allow that on their site, they should check out https://github.com/rtMediaWP/library/blob/master/media/rtmc_enable_multi_file_upload.php

**Comment by pranali333** [comment]
@BhargavBhandari90 

Could you please explain the intention behind this?

**Comment by BhargavBhandari90** [comment]
@pranali333 iPhone was not allowing multiple file uploads before v7.0.x that's why. 

After the solution of this, It will still not guaranty for the older IOS versions than v.7.0.0.

**Comment by kjnanda** [comment]
@BhargavBhandari90 I have cross-checked this issue for iOs version `7 to 9`

Till version 7 I can't upload multiple files. For version 8 and 9 I can upload multiple files. 

Works as expected. 👍

**Comment by SID177** [comment]
@pranali333 This issue was released in v4.4.4 and fixed by @BhargavBhandari90
