### ISSUE TITLE
Activity post generate incorrect markup

### ISSUE THREAD

**Issue by nitinpatil544** [rtMediaWP/rtMedia#968]
When i upload image without any text, rtMedia adding empty markup.
![image](https://user-images.githubusercontent.com/22708558/29274351-2fec0aea-8125-11e7-9866-bc083e0d13fe.png)

When i upload text with multiple paragraphs, rtMedia adding incorrect html markup. Can we put div tag instead of span. 
![image](https://user-images.githubusercontent.com/22708558/29274492-b1f0ed1c-8125-11e7-96ec-ea2e6a261a75.png)

**Comment by pranali333** [comment]
Hello @nitinpatil544 ,

Our team will look into this issue. Hopefully, it will be fixed soon. You can keep track on the progress here.

Thanks for reporting this to us.

Regards,
Pranali

**Comment by kjnanda** [comment]
Hi @nitinpatil544 

We have fixed this issue in the previous release only.
