### ISSUE TITLE
how to bring media as a separate page 

### ISSUE THREAD

**Issue by 122meters** [rtMediaWP/rtMedia#969]
how to bring media as a separate page

**Comment by pranali333** [comment]
Hello @122meters ,

If you want to create post/page for certain media then you can use gallery shortcode feature.
Here is the document where you can find more details - https://rtmedia.io/docs/features/gallery/

Let us know if you have any doubts.

Thanks

**Comment by 122meters** [comment]
Thank u so much.

**Comment by pranali333** [comment]
You are welcome @122meters, 

We are glad to know that it could be of your help.

I am closing this issue for now.
