### ISSUE TITLE
Showing title after paginate for album shortcode

### ISSUE THREAD

**Issue by BhargavBhandari90** [rtMediaWP/rtMedia#972]
If we use `[rtmedia_gallery global="true" media_type="album"]` and go to another page then it is showing album title.

Generally we have `media_title=true` for showing titles in shortcode. So it should follow this parameter.

**Comment by kjnanda** [comment]
This is working as expected. If we pass the `media_title=true` parameter then only it shows the title of media and albums are also treated as media only.
