### ISSUE TITLE
Media not showing if masonry view is disabled and width is set to zero.

### ISSUE THREAD

**Issue by sumeetsarna** [rtMediaWP/rtMedia#976]
Media not showing if masonry view is disabled and width is set to zero.

Updated Media Size Settings to:

![image](https://user-images.githubusercontent.com/8191145/30587081-8e6a856a-9d4f-11e7-956e-653d9c23daa3.png)

and disabled Masonry View from Display Settings. All media thumbnails are not visible now.

![image](https://user-images.githubusercontent.com/8191145/30587226-04c14924-9d50-11e7-8a46-3eb4409cb563.png)

![image](https://user-images.githubusercontent.com/8191145/30587394-9e72f68a-9d50-11e7-8141-517696171d0b.png)

**Comment by sumeetsarna** [comment]
This PR https://github.com/rtMediaWP/rtMedia/pull/977 solves this issue.

**Comment by kjnanda** [comment]
@BhargavBhandari90 Now, **I can see the media** when masonry view is diabled and width of media set to zero.

**Comment by sumeetsarna** [comment]
This is fixed now.
