### ISSUE TITLE
Styling needs improvement when masonry is disabled

### ISSUE THREAD

**Issue by sumeetsarna** [rtMediaWP/rtMedia#978]
When Masonry grid layout is enabled Media page looks like:

![image](https://user-images.githubusercontent.com/8191145/30637127-1839981a-9e15-11e7-8dd6-736a2916b2ef.png)

But when it is disabled it looks like:

![image](https://user-images.githubusercontent.com/8191145/30637514-2386d9a2-9e16-11e7-9fcb-9356428e4b1b.png)

In this case above Media Size Settings were:

![image](https://user-images.githubusercontent.com/8191145/30637575-49e91222-9e16-11e7-91c4-38e1e51315aa.png)

If we use Media Size Settings same as https://github.com/rtMediaWP/rtMedia/issues/976

then when Masonry is disabled it looks like:

![image](https://user-images.githubusercontent.com/8191145/30638344-bfab13a0-9e18-11e7-9ada-babf50880a51.png)

![image](https://user-images.githubusercontent.com/8191145/30638413-0004bd0c-9e19-11e7-9555-7e4bd2fccfcd.png)

Please check **Edit and Delete** on mouseover and the count.

Checked on Twenty Seventeen theme.

**Comment by kjnanda** [comment]
@BhargavBhandari90 Please check my comment below.

1. Check styling when `Masonry layout` is disabled. **`Done`**
Looks good to me 👍 

2. Check styling when media size width set to **`Zeor`** -->**UI still caters for this**. 

Please check below screenshots.

- UI for Albums - https://goo.gl/5dA7XT

- UI for All seperate Media -  https://goo.gl/vNufaM

**Comment by BhargavBhandari90** [comment]
@kjnanda  This has been fixed

**Comment by kjnanda** [comment]
@BhargavBhandari90 This looks good to me. 👍

**Comment by sumeetsarna** [comment]
@BhargavBhandari90  It still needs improvement.

For this Media Size Settings mentioned above:

![image](https://user-images.githubusercontent.com/8191145/31482242-268880b6-af45-11e7-8f76-54dbfb02133e.png)

The All Media page looks like:

![image](https://user-images.githubusercontent.com/8191145/31482232-184cc714-af45-11e7-981d-fd3976dcf26f.png)

Please check:

* [ ] 1.Edit and Delete on mouseover. The width should be same as the image.

* [ ] 2. The hover color should be lighter. If you check the image above `Delete` icon and first letter isn't properly visible

* [ ] 3. Albums display needs improvement

![image](https://user-images.githubusercontent.com/8191145/31482466-19bfe8c8-af46-11e7-8595-4e6142ab0c42.png)

* [ ] 3.1  Count should be closer to the album. Album's name should be centred. Less white space.

**Comment by sumeetsarna** [comment]
All points mentioned above looked good after regenerating thumbnails except Point 2.

![image](https://user-images.githubusercontent.com/8191145/31483487-37ee9e62-af4a-11e7-8d92-7f0fe7562463.png)

**Comment by BhargavBhandari90** [comment]
@sumeetsarna 

> 2. The hover color should be lighter. If you check the image above Delete icon and first letter isn't properly visible

It is default behavior from the Tewntyseventeen theme. The theme is adding black color on hover.

**Comment by sumeetsarna** [comment]
@BhargavBhandari90 Okay, then we may ignore this point. Looks fine in Twenty Sixteen and Twenty Fifteen
