### ISSUE TITLE
Issue with BuddyPress and rtMedia when we use the action `bp_before_member_header` for showing shortcode

### ISSUE THREAD

**Issue by BhargavBhandari90** [rtMediaWP/rtMedia#984]
If we use the given code, then it creates the problem

```
function rtmc_show_gallary() {

    if ( ! function_exists( 'bp_displayed_user_id' ) && ( function_exists( 'bp_is_user' ) && ! bp_is_user() ) ) {
        return;
    }
    $user_id = bp_displayed_user_id();
    echo do_shortcode( '[rtmedia_gallery global="true"]' );

}
add_action( 'bp_before_member_header', 'rtmc_show_gallary' );

**Comment by BhargavBhandari90** [comment]
@pranali333 https://github.com/rtMediaWP/library/blob/master/media/RTMC_Gallery_Shortcode.php

**Comment by kjnanda** [comment]
@BhargavBhandari90 Please check my comment below.

1. If I used this snippet, I am able to see the Gallery media above the Cover image. But media comes in `verticle` alignment. Which doesn't look proper. 
Please check this link - https://goo.gl/yp2BrW

2. After I add code snippet, I am not able to see the `Upload panel` on the front end. Which should not happen.
Please check this link - https://goo.gl/VfqRVZ

**Comment by BhargavBhandari90** [comment]
@kjnanda Ignore the code given in first comment. This has been fixed in https://github.com/rtMediaWP/library/blob/master/media/RTMC_Gallery_Shortcode.php.

**Comment by BhargavBhandari90** [comment]
> If I used this snippet, I am able to see the Gallery media above the Cover image. But media comes in verticle alignment. Which doesn't look proper.
Please check this link - https://goo.gl/yp2BrW

This is not our problem as this is custom code.

**Comment by kjnanda** [comment]
@BhargavBhandari90 In reference of this - 

> @kjnanda Ignore the code given in the first comment. This has been fixed in https://github.com/rtMediaWP/library/blob/master/media/RTMC_Gallery_Shortcode.php.

I can see `Upload Panel` using this code.

Done. 👍
